# Generated by Django 5.2.8 on 2025-11-19 02:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0006_document_account_number_document_customer_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Unique secure token for accessing the share",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("VIEW_ONLY", "View Only"),
                            ("VIEW_DOWNLOAD", "View and Download"),
                            ("VIEW_DOWNLOAD_COMMENT", "View, Download, and Comment"),
                        ],
                        default="VIEW_ONLY",
                        max_length=30,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of password (if password-protected)",
                        max_length=128,
                        null=True,
                    ),
                ),
                ("is_password_protected", models.BooleanField(default=False)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the share expires (null = never expires)",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "recipient_emails",
                    models.JSONField(
                        blank=True, default=list, help_text="List of email addresses to notify"
                    ),
                ),
                ("access_count", models.IntegerField(default=0, help_text="Total access count")),
                (
                    "download_count",
                    models.IntegerField(default=0, help_text="Total download count"),
                ),
                ("view_count", models.IntegerField(default=0, help_text="Total view count")),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allow_public_access",
                    models.BooleanField(default=True, help_text="Allow anyone with link to access"),
                ),
                (
                    "max_access_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of accesses allowed (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Internal notes about this share"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="documents.document",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revoked_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Share",
                "verbose_name_plural": "Shares",
                "db_table": "shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("view", "View"),
                            ("download", "Download"),
                            ("comment", "Comment"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_records",
                        to="sharing.share",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="share_accesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Share Access",
                "verbose_name_plural": "Share Accesses",
                "db_table": "share_accesses",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="share",
            index=models.Index(fields=["token"], name="shares_token_b60364_idx"),
        ),
        migrations.AddIndex(
            model_name="share",
            index=models.Index(
                fields=["is_active", "expires_at"], name="shares_is_acti_29fcd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="share",
            index=models.Index(
                fields=["created_by", "created_at"], name="shares_created_bb0d66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareaccess",
            index=models.Index(
                fields=["share", "-accessed_at"], name="share_acces_share_i_d6f8e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareaccess",
            index=models.Index(
                fields=["access_type", "-accessed_at"], name="share_acces_access__5f4621_idx"
            ),
        ),
    ]
