# Generated by Django 5.2.8 on 2025-11-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0003_notification_notificationpreferences"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_2d3764_idx",
            old_name="notificatio_recipie_a52b88_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_recipie_dde14f_idx",
            old_name="notificatio_recipie_e3f95b_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_notific_498289_idx",
            old_name="notificatio_notific_4c79e6_idx",
        ),
        migrations.RenameIndex(
            model_name="shareditemaccess",
            new_name="shared_item_recipie_f0a0bc_idx",
            old_name="shared_item_recipie_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="shareditemaccess",
            new_name="shared_item_recipie_06db4d_idx",
            old_name="shared_item_recipie_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="shareditemaccess",
            new_name="shared_item_recipie_0652af_idx",
            old_name="shared_item_recipie_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="shareditemaccess",
            new_name="shared_item_recipie_bef69b_idx",
            old_name="shared_item_recipie_j1k2l3_idx",
        ),
        migrations.RenameIndex(
            model_name="shareditemaccess",
            new_name="shared_item_recipie_3081b9_idx",
            old_name="shared_item_recipie_m4n5o6_idx",
        ),
        migrations.RenameIndex(
            model_name="shareditemaccess",
            new_name="shared_item_resourc_28dab6_idx",
            old_name="shared_item_resourc_p7q8r9_idx",
        ),
        migrations.RenameIndex(
            model_name="shareditemaccess",
            new_name="shared_item_recipie_da11d0_idx",
            old_name="shared_item_recipie_s1t2u3_idx",
        ),
        migrations.RenameIndex(
            model_name="shareinvitation",
            new_name="share_invit_invited_3da1cc_idx",
            old_name="share_invit_invited_v4w5x6_idx",
        ),
        migrations.RenameIndex(
            model_name="shareinvitation",
            new_name="share_invit_invited_0600dc_idx",
            old_name="share_invit_invited_y7z8a9_idx",
        ),
        migrations.RenameIndex(
            model_name="shareinvitation",
            new_name="share_invit_resourc_edada5_idx",
            old_name="share_invit_resourc_b1c2d3_idx",
        ),
    ]
