# Generated by Django 5.2.8 on 2026-03-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sharing",
            "0004_rename_notificatio_recipie_a52b88_idx_notificatio_recipie_2d3764_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("SHARE_RECEIVED", "Document/Folder shared with you"),
                    ("SHARE_INVITATION", "Share invitation received"),
                    ("ACCESS_REQUEST", "Access request submitted"),
                    ("ACCESS_GRANTED", "Access request approved"),
                    ("ACCESS_DENIED", "Access request denied"),
                    ("SHARE_REVOKED", "Share access revoked"),
                    ("SHARE_EXPIRING", "Share about to expire"),
                    ("INVITATION_ACCEPTED", "Share invitation accepted"),
                    ("INVITATION_DECLINED", "Share invitation declined"),
                    ("WEEKLY_DIGEST", "Weekly sharing digest"),
                    ("STEP_APPROVED", "Procedure step approved"),
                    ("STEP_CHANGES_REQ", "Changes requested on procedure step"),
                    ("PROCEDURE_APPROVED", "Procedure approved"),
                    ("PROCEDURE_REJECTED", "Procedure rejected"),
                    ("REVIEW_ASSIGNED", "Assigned as reviewer"),
                    ("TRAINING_ASSIGNED", "Training assigned"),
                ],
                max_length=30,
            ),
        ),
    ]
