# Generated by Django 5.2.8 on 2025-11-28 02:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0015_document_states"),
        ("organizations", "0004_add_company_registration_fields"),
        ("users", "0012_add_share_protection_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        help_text="Snapshot of template name at time of creation", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "current_step",
                    models.PositiveIntegerField(
                        default=1, help_text="Current step number (1-based)"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, help_text="Notes from the initiator")),
                (
                    "outcome_reason",
                    models.TextField(blank=True, help_text="Reason for rejection/cancellation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_instances",
                        to="documents.document",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_workflows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_instances",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Instance",
                "verbose_name_plural": "Workflow Instances",
                "db_table": "workflow_instances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("step_order", models.PositiveIntegerField()),
                ("step_name", models.CharField(max_length=255)),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("APPROVAL", "Approval"),
                            ("REVIEW", "Review"),
                            ("SIGN_OFF", "Sign-off"),
                            ("NOTIFICATION", "Notification"),
                            ("PARALLEL", "Parallel Approval"),
                        ],
                        default="APPROVAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SKIPPED", "Skipped"),
                            ("DELEGATED", "Delegated"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        blank=True,
                        help_text="The action taken (APPROVE, REJECT, etc.)",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_escalated", models.BooleanField(default=False)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "comment",
                    models.TextField(blank=True, help_text="Comment provided with the action"),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delegated_from",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original assignee if this task was delegated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delegated_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Task",
                "verbose_name_plural": "Workflow Tasks",
                "db_table": "workflow_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content", models.TextField()),
                (
                    "mentions",
                    models.JSONField(
                        blank=True, default=list, help_text="User IDs mentioned in this comment"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="workflows.workflowinstance",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="workflows.workflowtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Comment",
                "verbose_name_plural": "Workflow Comments",
                "db_table": "workflow_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Workflow Created"),
                            ("STARTED", "Workflow Started"),
                            ("TASK_ASSIGNED", "Task Assigned"),
                            ("TASK_APPROVED", "Task Approved"),
                            ("TASK_REJECTED", "Task Rejected"),
                            ("TASK_DELEGATED", "Task Delegated"),
                            ("TASK_ESCALATED", "Task Escalated"),
                            ("TASK_EXPIRED", "Task Expired"),
                            ("STEP_COMPLETED", "Step Completed"),
                            ("WORKFLOW_APPROVED", "Workflow Approved"),
                            ("WORKFLOW_REJECTED", "Workflow Rejected"),
                            ("WORKFLOW_CANCELLED", "Workflow Cancelled"),
                            ("WORKFLOW_EXPIRED", "Workflow Expired"),
                            ("COMMENT_ADDED", "Comment Added"),
                            ("REMINDER_SENT", "Reminder Sent"),
                        ],
                        max_length=30,
                    ),
                ),
                ("details", models.TextField(blank=True, help_text="Human-readable description")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (previous assignee, etc.)",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="workflows.workflowinstance",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="workflows.workflowtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Audit Log",
                "verbose_name_plural": "Workflow Audit Logs",
                "db_table": "workflow_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Template name", max_length=255)),
                ("description", models.TextField(blank=True, help_text="Template description")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Category for grouping (e.g., Contracts, Compliance, Finance)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template can be used"
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="System templates cannot be deleted by users"
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "default_due_days",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Default number of days to complete the workflow",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "applicable_document_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of document types this workflow applies to (empty = all)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "times_used",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this template was used"
                    ),
                ),
                (
                    "avg_completion_days",
                    models.FloatField(
                        blank=True,
                        help_text="Average days to complete workflows using this template",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_workflow_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization this template belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_templates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Template",
                "verbose_name_plural": "Workflow Templates",
                "db_table": "workflow_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text='Step name (e.g., "Legal Review")', max_length=255),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(help_text="Execution order (1-based)")),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("APPROVAL", "Approval"),
                            ("REVIEW", "Review"),
                            ("SIGN_OFF", "Sign-off"),
                            ("NOTIFICATION", "Notification"),
                            ("PARALLEL", "Parallel Approval"),
                        ],
                        default="APPROVAL",
                        max_length=20,
                    ),
                ),
                (
                    "approval_type",
                    models.CharField(
                        choices=[
                            ("ALL", "All must approve"),
                            ("ANY", "Any one can approve"),
                            ("MAJORITY", "Majority must approve"),
                            ("PERCENTAGE", "Percentage threshold"),
                        ],
                        default="ALL",
                        help_text="For parallel steps, how approval is determined",
                        max_length=20,
                    ),
                ),
                (
                    "approval_percentage",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Required approval percentage (if approval_type is PERCENTAGE)",
                        null=True,
                    ),
                ),
                (
                    "assigned_role",
                    models.CharField(
                        blank=True,
                        help_text='Role that can handle this step (e.g., "MANAGER", "LEGAL_COUNSEL")',
                        max_length=100,
                    ),
                ),
                (
                    "sla_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Hours to complete this step (for SLA tracking)",
                        null=True,
                    ),
                ),
                (
                    "escalation_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Hours after which to escalate (must be less than sla_hours)",
                        null=True,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Conditions that must be met for this step to execute",
                    ),
                ),
                (
                    "auto_approve_if_same_user",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-approve if the same user approved the previous step",
                    ),
                ),
                (
                    "require_comment",
                    models.BooleanField(
                        default=False, help_text="Require a comment when approving/rejecting"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department that can handle this step",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_workflow_steps",
                        to="users.department",
                    ),
                ),
                (
                    "assigned_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific users assigned to this step",
                        related_name="assigned_workflow_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalate_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User to escalate to if SLA is at risk",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalation_target_steps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="workflows.workflowtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Step",
                "verbose_name_plural": "Workflow Steps",
                "db_table": "workflow_steps",
                "ordering": ["template", "order"],
            },
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="workflows.workflowtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(
                fields=["assigned_to", "status"], name="workflow_ta_assigne_16a63b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(
                fields=["workflow", "step_order"], name="workflow_ta_workflo_2a0021_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(fields=["due_date"], name="workflow_ta_due_dat_97fce6_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowtask",
            index=models.Index(fields=["status", "is_read"], name="workflow_ta_status_374c9f_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowauditlog",
            index=models.Index(
                fields=["workflow", "timestamp"], name="workflow_au_workflo_64ae1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowauditlog",
            index=models.Index(
                fields=["actor", "timestamp"], name="workflow_au_actor_i_dfee13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowauditlog",
            index=models.Index(fields=["action"], name="workflow_au_action_54259e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="workflowtemplate",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="workflowstep",
            unique_together={("template", "order")},
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(fields=["status", "due_date"], name="workflow_in_status_5dc74c_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(fields=["document"], name="workflow_in_documen_8a323d_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowinstance",
            index=models.Index(fields=["initiated_by"], name="workflow_in_initiat_582c26_idx"),
        ),
    ]
