# Generated by Django 5.2.8 on 2025-11-28 05:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0008_update_smart_folder_icon_color_choices"),
        ("organizations", "0004_add_company_registration_fields"),
        ("users", "0012_add_share_protection_fields"),
        ("workflows", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Name for this API key", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the integration"),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 chars of key (for identification)", max_length=8
                    ),
                ),
                ("key_hash", models.CharField(help_text="SHA-256 hash of full key", max_length=64)),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="List of allowed operations: read_workflows, write_workflows, trigger_workflows, etc.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rate_limit_per_minute",
                    models.PositiveIntegerField(
                        default=60, help_text="Maximum requests per minute (0 = unlimited)"
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed IP addresses (empty = all allowed)",
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(blank=True, help_text="URL to receive webhook notifications"),
                ),
                (
                    "webhook_secret",
                    models.CharField(
                        blank=True,
                        help_text="Secret for webhook signature verification",
                        max_length=64,
                    ),
                ),
                (
                    "webhook_events",
                    models.JSONField(
                        default=list,
                        help_text="Events to send to webhook: workflow.created, task.completed, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_api_keys",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "External API Key",
                "verbose_name_plural": "External API Keys",
                "db_table": "workflow_external_api_keys",
                "indexes": [
                    models.Index(
                        fields=["key_prefix", "is_active"], name="workflow_ex_key_pre_0c934d_idx"
                    ),
                    models.Index(
                        fields=["organization", "is_active"], name="workflow_ex_organiz_3136c7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkflowAutoTriggerRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Rule name for identification", max_length=255),
                ),
                ("description", models.TextField(blank=True, help_text="Rule description")),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether this rule is active"),
                ),
                (
                    "document_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of document types that trigger this rule (empty = all)",
                    ),
                ),
                (
                    "include_subfolders",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to include subfolders when checking folder condition",
                    ),
                ),
                (
                    "confidentiality_levels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Confidentiality levels that trigger this rule (empty = all)",
                    ),
                ),
                (
                    "min_file_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Minimum file size in bytes to trigger (null = no minimum)",
                        null=True,
                    ),
                ),
                (
                    "max_file_size",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Maximum file size in bytes to trigger (null = no maximum)",
                        null=True,
                    ),
                ),
                (
                    "additional_conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional JSON conditions for complex matching",
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        help_text="Priority for auto-triggered workflows",
                        max_length=20,
                    ),
                ),
                (
                    "due_days_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Override default due days from template (null = use template default)",
                        null=True,
                    ),
                ),
                (
                    "auto_start",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically start the workflow (vs create in DRAFT status)",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100, help_text="Rule priority (lower numbers are evaluated first)"
                    ),
                ),
                (
                    "stop_processing",
                    models.BooleanField(
                        default=True, help_text="Stop evaluating other rules if this rule matches"
                    ),
                ),
                (
                    "times_triggered",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this rule has triggered"
                    ),
                ),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True, help_text="When this rule was last triggered", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_auto_trigger_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_auto_trigger_rules",
                        to="organizations.organization",
                    ),
                ),
                (
                    "trigger_departments",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Departments whose documents trigger this rule (empty = all)",
                        related_name="workflow_auto_trigger_rules",
                        to="users.department",
                    ),
                ),
                (
                    "trigger_folders",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Folders where uploaded documents trigger this rule (empty = all)",
                        related_name="auto_trigger_rules",
                        to="folders.folder",
                    ),
                ),
                (
                    "workflow_template",
                    models.ForeignKey(
                        help_text="Workflow template to trigger when conditions are met",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_trigger_rules",
                        to="workflows.workflowtemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Auto-Trigger Rule",
                "verbose_name_plural": "Workflow Auto-Trigger Rules",
                "db_table": "workflow_auto_trigger_rules",
                "ordering": ["priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority"], name="workflow_au_is_acti_cefeb9_idx"
                    ),
                    models.Index(
                        fields=["organization", "is_active"], name="workflow_au_organiz_53035a_idx"
                    ),
                ],
            },
        ),
    ]
