# Generated by Django 5.2.8 on 2026-03-09 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0005_finalize_generic_target"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="workflowinstance",
            name="workflow_in_documen_8a323d_idx",
        ),
    ]
