# Generated by Django 5.2.8 on 2025-11-29 14:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "log_auth_events",
                    models.BooleanField(default=True, help_text="Log authentication events"),
                ),
                (
                    "log_document_events",
                    models.BooleanField(default=True, help_text="Log document operations"),
                ),
                (
                    "log_folder_events",
                    models.BooleanField(default=True, help_text="Log folder operations"),
                ),
                (
                    "log_user_events",
                    models.BooleanField(default=True, help_text="Log user management events"),
                ),
                (
                    "log_permission_events",
                    models.BooleanField(default=True, help_text="Log permission changes"),
                ),
                (
                    "log_search_events",
                    models.BooleanField(default=False, help_text="Log search queries"),
                ),
                ("log_api_events", models.BooleanField(default=True, help_text="Log API access")),
                (
                    "log_system_events",
                    models.BooleanField(default=True, help_text="Log system events"),
                ),
                ("alert_on_failed_logins", models.BooleanField(default=True)),
                ("failed_login_threshold", models.PositiveIntegerField(default=5)),
                ("alert_on_bulk_deletion", models.BooleanField(default=True)),
                ("bulk_deletion_threshold", models.PositiveIntegerField(default=10)),
                ("alert_on_permission_changes", models.BooleanField(default=True)),
                (
                    "alert_recipients",
                    models.JSONField(default=list, help_text="Email addresses for alerts"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Audit Configuration",
                "verbose_name_plural": "Audit Configurations",
                "db_table": "audit_configuration",
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "platform_name",
                    models.CharField(
                        default="Digital Filing Cabinet",
                        help_text="Platform name displayed to users",
                        max_length=100,
                    ),
                ),
                (
                    "platform_tagline",
                    models.CharField(
                        default="Enterprise Document Management",
                        help_text="Platform tagline",
                        max_length=255,
                    ),
                ),
                (
                    "support_email",
                    models.EmailField(
                        default="support@dfc.com",
                        help_text="Platform support email",
                        max_length=254,
                    ),
                ),
                (
                    "support_phone",
                    models.CharField(blank=True, help_text="Platform support phone", max_length=50),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable maintenance mode (blocks all non-admin access)",
                    ),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="The system is currently undergoing scheduled maintenance. Please check back soon.",
                        help_text="Message displayed during maintenance",
                    ),
                ),
                (
                    "maintenance_allowed_ips",
                    models.JSONField(
                        default=list, help_text="List of IP addresses allowed during maintenance"
                    ),
                ),
                (
                    "allow_registration",
                    models.BooleanField(
                        default=True, help_text="Allow new organization registration"
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=True, help_text="Require email verification for new users"
                    ),
                ),
                (
                    "auto_approve_organizations",
                    models.BooleanField(
                        default=True, help_text="Auto-approve new organization registrations"
                    ),
                ),
                (
                    "default_trial_days",
                    models.PositiveIntegerField(
                        default=14,
                        help_text="Default trial period for new organizations",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "global_rate_limit",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Global API rate limit per minute",
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                    ),
                ),
                (
                    "max_file_size_mb",
                    models.PositiveIntegerField(
                        default=500,
                        help_text="Maximum file upload size in MB",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5000),
                        ],
                    ),
                ),
                (
                    "allowed_file_types",
                    models.JSONField(
                        default=list,
                        help_text="List of allowed file extensions (empty = all allowed)",
                    ),
                ),
                (
                    "blocked_file_types",
                    models.JSONField(default=list, help_text="List of blocked file extensions"),
                ),
                (
                    "email_from_name",
                    models.CharField(
                        default="Digital Filing Cabinet",
                        help_text="From name for system emails",
                        max_length=100,
                    ),
                ),
                (
                    "email_from_address",
                    models.EmailField(
                        default="noreply@dfc.com",
                        help_text="From address for system emails",
                        max_length=254,
                    ),
                ),
                (
                    "smtp_host",
                    models.CharField(blank=True, help_text="SMTP server host", max_length=255),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=587, help_text="SMTP server port"),
                ),
                (
                    "smtp_use_tls",
                    models.BooleanField(default=True, help_text="Use TLS for SMTP connection"),
                ),
                (
                    "smtp_username",
                    models.CharField(
                        blank=True, help_text="SMTP authentication username", max_length=255
                    ),
                ),
                (
                    "storage_provider",
                    models.CharField(
                        choices=[
                            ("minio", "MinIO"),
                            ("s3", "Amazon S3"),
                            ("azure", "Azure Blob Storage"),
                            ("gcs", "Google Cloud Storage"),
                        ],
                        default="minio",
                        help_text="Primary storage provider",
                        max_length=50,
                    ),
                ),
                (
                    "storage_region",
                    models.CharField(
                        blank=True, help_text="Storage region/endpoint", max_length=50
                    ),
                ),
                (
                    "storage_bucket",
                    models.CharField(
                        default="dfc-documents", help_text="Default storage bucket", max_length=100
                    ),
                ),
                (
                    "enable_redundant_storage",
                    models.BooleanField(
                        default=False, help_text="Enable redundant storage for backups"
                    ),
                ),
                (
                    "search_provider",
                    models.CharField(
                        choices=[
                            ("elasticsearch", "Elasticsearch"),
                            ("opensearch", "OpenSearch"),
                            ("database", "Database Full-Text Search"),
                        ],
                        default="elasticsearch",
                        help_text="Search engine provider",
                        max_length=50,
                    ),
                ),
                (
                    "search_index_delay_seconds",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Delay before indexing new documents",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(300),
                        ],
                    ),
                ),
                (
                    "enable_ocr",
                    models.BooleanField(default=True, help_text="Enable OCR for scanned documents"),
                ),
                (
                    "ocr_languages",
                    models.JSONField(default=list, help_text="Supported OCR languages"),
                ),
                (
                    "audit_retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Days to retain audit logs",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(3650),
                        ],
                    ),
                ),
                (
                    "enable_gdpr_compliance",
                    models.BooleanField(default=True, help_text="Enable GDPR compliance features"),
                ),
                (
                    "data_residency_required",
                    models.BooleanField(
                        default=False, help_text="Require data residency in specific regions"
                    ),
                ),
                (
                    "enable_public_api",
                    models.BooleanField(default=True, help_text="Enable public API access"),
                ),
                (
                    "enable_webhooks",
                    models.BooleanField(default=True, help_text="Enable webhook integrations"),
                ),
                (
                    "enable_third_party_integrations",
                    models.BooleanField(default=True, help_text="Enable third-party integrations"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
        migrations.CreateModel(
            name="PlatformAnnouncement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_dismissible", models.BooleanField(default=True)),
                ("target_all_users", models.BooleanField(default=True)),
                (
                    "target_plans",
                    models.JSONField(
                        default=list, help_text="List of subscription plans to target (empty = all)"
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Announcement",
                "verbose_name_plural": "Platform Announcements",
                "db_table": "platform_announcements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemHealthCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("degraded", "Degraded"),
                            ("unhealthy", "Unhealthy"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("response_time_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("details", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "System Health Check",
                "verbose_name_plural": "System Health Checks",
                "db_table": "system_health_checks",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["service_name", "-checked_at"],
                        name="system_heal_service_e6a43f_idx",
                    ),
                    models.Index(
                        fields=["status", "-checked_at"], name="system_heal_status_bb83a4_idx"
                    ),
                ],
            },
        ),
    ]
