# Generated by Django 5.2.8 on 2025-11-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="storage_quota_gb",
            field=models.IntegerField(
                default=100, help_text="Storage quota in gigabytes for this department"
            ),
        ),
    ]
