# Generated by Django 5.2.8 on 2025-11-19 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_department_storage_quota_gb"),
    ]

    operations = [
        migrations.CreateModel(
            name="MFASettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="mfa_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("mfa_enabled", models.BooleanField(default=False)),
                (
                    "mfa_enforced",
                    models.BooleanField(
                        default=False,
                        help_text="If True, user cannot disable MFA (admin/superuser enforcement)",
                    ),
                ),
                ("totp_enabled", models.BooleanField(default=False)),
                ("totp_confirmed", models.BooleanField(default=False)),
                ("totp_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("disabled_at", models.DateTimeField(blank=True, null=True)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_failures", models.IntegerField(default=0)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "MFA Settings",
                "verbose_name_plural": "MFA Settings",
                "db_table": "mfa_settings",
            },
        ),
        migrations.CreateModel(
            name="MFABackupCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("used_from_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_backup_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mfa_backup_codes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="mfa_backup__user_id_870ec4_idx"
                    ),
                    models.Index(fields=["used", "user"], name="mfa_backup__used_4deb4a_idx"),
                ],
            },
        ),
    ]
