# Generated by Django 5.2.8 on 2025-11-19 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_create_default_organization"),
        ("users", "0004_add_organization_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this department belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="departments",
                to="organizations.organization",
            ),
        ),
    ]
