# Generated by Django 5.2.8 on 2025-11-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_organization_to_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address_line1",
            field=models.CharField(blank=True, help_text="Primary address line", max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address_line2",
            field=models.CharField(
                blank=True, help_text="Secondary address line (optional)", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, help_text="City", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(blank=True, help_text="Country", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="job_title",
            field=models.CharField(blank=True, help_text="User job title/position", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="marketing_consent",
            field=models.BooleanField(
                default=False, help_text="User consent for marketing communications"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="postal_code",
            field=models.CharField(blank=True, help_text="Postal/ZIP code", max_length=20),
        ),
        migrations.AddField(
            model_name="customuser",
            name="privacy_accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when user accepted Privacy Policy", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(blank=True, help_text="State/Province/Region", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when user accepted Terms of Service", null=True
            ),
        ),
    ]
