# Generated by Django 5.2.8 on 2025-11-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_add_company_registration_fields"),
        ("users", "0006_add_user_profile_and_address_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "code")},
        ),
    ]
