# Generated by Django 5.2.8 on 2025-11-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_passwordresetattempt_passwordhistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, help_text="Email address to verify", max_length=254
                    ),
                ),
                ("code", models.CharField(help_text="6-digit OTP code", max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="Expiration timestamp")),
                (
                    "is_used",
                    models.BooleanField(default=False, help_text="Whether this OTP has been used"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether verification was successful"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when OTP was verified", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address that requested the OTP", null=True
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(default=0, help_text="Number of verification attempts"),
                ),
            ],
            options={
                "verbose_name": "Email OTP",
                "verbose_name_plural": "Email OTPs",
                "db_table": "email_otp",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["email", "-created_at"], name="email_otp_email_c417be_idx"
                    ),
                    models.Index(fields=["code"], name="email_otp_code_4c73a1_idx"),
                    models.Index(fields=["expires_at"], name="email_otp_expires_4fc98d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Phone number to verify (with country code)",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(help_text="6-digit OTP code", max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="Expiration timestamp")),
                (
                    "is_used",
                    models.BooleanField(default=False, help_text="Whether this OTP has been used"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether verification was successful"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp when OTP was verified", null=True
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address that requested the OTP", null=True
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(default=0, help_text="Number of verification attempts"),
                ),
            ],
            options={
                "verbose_name": "Phone OTP",
                "verbose_name_plural": "Phone OTPs",
                "db_table": "phone_otp",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "-created_at"], name="phone_otp_phone_n_9551f7_idx"
                    ),
                    models.Index(fields=["code"], name="phone_otp_code_235fcb_idx"),
                    models.Index(fields=["expires_at"], name="phone_otp_expires_8e24f0_idx"),
                ],
            },
        ),
    ]
