# Generated by Django 5.2.8 on 2025-11-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_add_favorite_collections"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritecollection",
            name="share_expires_at",
            field=models.DateTimeField(
                blank=True, help_text="When the share expires (null = never expires)", null=True
            ),
        ),
        migrations.AddField(
            model_name="favoritecollection",
            name="share_password",
            field=models.CharField(
                blank=True,
                help_text="Hashed password for accessing the shared collection",
                max_length=128,
                null=True,
            ),
        ),
    ]
