# Generated by Django 5.2.8 on 2025-11-29 11:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_add_share_protection_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="notification_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(default=True, help_text="Enable email notifications"),
                ),
                (
                    "email_document_shared",
                    models.BooleanField(
                        default=True, help_text="Email when document is shared with you"
                    ),
                ),
                (
                    "email_workflow_assigned",
                    models.BooleanField(
                        default=True, help_text="Email when workflow task is assigned"
                    ),
                ),
                (
                    "email_workflow_completed",
                    models.BooleanField(
                        default=True, help_text="Email when your workflow task is completed"
                    ),
                ),
                (
                    "email_retention_reminder",
                    models.BooleanField(
                        default=True, help_text="Email reminders about document retention"
                    ),
                ),
                (
                    "email_weekly_digest",
                    models.BooleanField(default=True, help_text="Receive weekly activity digest"),
                ),
                (
                    "email_security_alerts",
                    models.BooleanField(
                        default=True, help_text="Security-related alerts (always recommended)"
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(default=True, help_text="Enable in-app notifications"),
                ),
                (
                    "in_app_document_shared",
                    models.BooleanField(default=True, help_text="Notify when document is shared"),
                ),
                (
                    "in_app_workflow_updates",
                    models.BooleanField(default=True, help_text="Notify about workflow updates"),
                ),
                (
                    "in_app_mentions",
                    models.BooleanField(
                        default=True, help_text="Notify when mentioned in comments"
                    ),
                ),
                (
                    "in_app_system_updates",
                    models.BooleanField(default=True, help_text="System update notifications"),
                ),
                (
                    "desktop_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable browser desktop notifications"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable quiet hours (no notifications)"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, help_text="Start of quiet hours", null=True),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, help_text="End of quiet hours", null=True),
                ),
                (
                    "notification_sound",
                    models.BooleanField(default=True, help_text="Play sound for notifications"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Settings",
                "verbose_name_plural": "Notification Settings",
                "db_table": "notification_settings",
            },
        ),
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="security_settings",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session_timeout",
                    models.IntegerField(
                        choices=[
                            (15, "15 minutes"),
                            (30, "30 minutes"),
                            (60, "1 hour"),
                            (120, "2 hours"),
                            (240, "4 hours"),
                            (480, "8 hours"),
                        ],
                        default=60,
                        help_text="Session timeout in minutes",
                    ),
                ),
                (
                    "require_mfa_for_sensitive",
                    models.BooleanField(
                        default=True, help_text="Require MFA for sensitive operations"
                    ),
                ),
                (
                    "login_notification_email",
                    models.BooleanField(default=True, help_text="Email notification on new login"),
                ),
                (
                    "login_notification_new_device",
                    models.BooleanField(default=True, help_text="Notify on login from new device"),
                ),
                (
                    "login_notification_new_location",
                    models.BooleanField(
                        default=True, help_text="Notify on login from new location"
                    ),
                ),
                (
                    "ip_whitelist",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="JSON array of allowed IP addresses/ranges",
                    ),
                ),
                (
                    "api_access_enabled",
                    models.BooleanField(
                        default=False, help_text="Allow API access with personal tokens"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Security Settings",
                "verbose_name_plural": "Security Settings",
                "db_table": "security_settings",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark"), ("system", "System")],
                        default="system",
                        help_text="UI theme preference",
                        max_length=20,
                    ),
                ),
                (
                    "display_density",
                    models.CharField(
                        choices=[("comfortable", "Comfortable"), ("compact", "Compact")],
                        default="comfortable",
                        help_text="UI density preference",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("es", "Spanish"),
                            ("de", "German"),
                            ("pt", "Portuguese"),
                            ("zh", "Chinese"),
                            ("ja", "Japanese"),
                        ],
                        default="en",
                        help_text="Preferred language",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        choices=[
                            ("UTC", "UTC"),
                            ("America/New_York", "Eastern Time (US)"),
                            ("America/Chicago", "Central Time (US)"),
                            ("America/Denver", "Mountain Time (US)"),
                            ("America/Los_Angeles", "Pacific Time (US)"),
                            ("Europe/London", "London"),
                            ("Europe/Paris", "Paris"),
                            ("Europe/Berlin", "Berlin"),
                            ("Asia/Tokyo", "Tokyo"),
                            ("Asia/Shanghai", "Shanghai"),
                            ("Asia/Singapore", "Singapore"),
                            ("Australia/Sydney", "Sydney"),
                        ],
                        default="UTC",
                        help_text="Preferred timezone",
                        max_length=50,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("MM/DD/YYYY", "MM/DD/YYYY"),
                            ("DD/MM/YYYY", "DD/MM/YYYY"),
                            ("YYYY-MM-DD", "YYYY-MM-DD"),
                        ],
                        default="MM/DD/YYYY",
                        help_text="Preferred date format",
                        max_length=20,
                    ),
                ),
                (
                    "time_format",
                    models.CharField(
                        choices=[("12h", "12-hour"), ("24h", "24-hour")],
                        default="12h",
                        help_text="Preferred time format",
                        max_length=10,
                    ),
                ),
                (
                    "default_document_view",
                    models.CharField(
                        choices=[("grid", "Grid View"), ("list", "List View")],
                        default="list",
                        help_text="Default view for document lists",
                        max_length=10,
                    ),
                ),
                (
                    "items_per_page",
                    models.IntegerField(
                        default=25,
                        help_text="Number of items per page (10-100)",
                        validators=[
                            django.core.validators.MinValueValidator(10),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "show_file_extensions",
                    models.BooleanField(
                        default=True, help_text="Show file extensions in document names"
                    ),
                ),
                (
                    "show_thumbnails",
                    models.BooleanField(
                        default=True, help_text="Show document thumbnails when available"
                    ),
                ),
                (
                    "start_page",
                    models.CharField(
                        default="dashboard", help_text="Default page after login", max_length=50
                    ),
                ),
                (
                    "sidebar_collapsed",
                    models.BooleanField(
                        default=False, help_text="Remember sidebar collapsed state"
                    ),
                ),
                (
                    "show_recent_items",
                    models.BooleanField(default=True, help_text="Show recent items in sidebar"),
                ),
                (
                    "recent_items_count",
                    models.IntegerField(
                        default=10,
                        help_text="Number of recent items to display",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(25),
                        ],
                    ),
                ),
                (
                    "enable_keyboard_shortcuts",
                    models.BooleanField(default=True, help_text="Enable keyboard shortcuts"),
                ),
                (
                    "enable_animations",
                    models.BooleanField(default=True, help_text="Enable UI animations"),
                ),
                (
                    "high_contrast_mode",
                    models.BooleanField(
                        default=False, help_text="Enable high contrast mode for accessibility"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preferences",
            },
        ),
    ]
