# Generated by Django 5.2.8 on 2025-12-02 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_add_user_settings_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="MFAEnforcementPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "enforcement_level",
                    models.CharField(
                        choices=[
                            ("optional", "Optional"),
                            ("recommended", "Recommended"),
                            ("required", "Required"),
                            ("strict", "Strict (No bypass allowed)"),
                        ],
                        default="optional",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all_users", "All Users"),
                            ("admin_users", "Admin Users Only"),
                            ("department", "Specific Department"),
                            ("role", "Specific Role"),
                            ("custom", "Custom Criteria"),
                        ],
                        default="all_users",
                        max_length=20,
                    ),
                ),
                (
                    "scope_criteria",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON criteria for custom scopes (e.g., {"departments": ["IT", "Finance"]})',
                    ),
                ),
                (
                    "grace_period_days",
                    models.IntegerField(
                        default=7, help_text="Days before enforcement becomes mandatory"
                    ),
                ),
                (
                    "enforcement_start_date",
                    models.DateTimeField(
                        blank=True, help_text="When enforcement begins", null=True
                    ),
                ),
                (
                    "allowed_methods",
                    models.JSONField(
                        default=list,
                        help_text='List of allowed MFA methods (e.g., ["totp", "sms", "email"])',
                    ),
                ),
                ("send_reminders", models.BooleanField(default=True)),
                (
                    "reminder_days_before",
                    models.JSONField(
                        default=list,
                        help_text="Days before deadline to send reminders (e.g., [7, 3, 1])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_mfa_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MFA Enforcement Policy",
                "verbose_name_plural": "MFA Enforcement Policies",
                "db_table": "mfa_enforcement_policies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginRiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("device_fingerprint", models.CharField(blank=True, max_length=64)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("is_vpn", models.BooleanField(default=False)),
                ("is_tor", models.BooleanField(default=False)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("risk_score", models.IntegerField(default=0, help_text="Risk score from 0-100")),
                (
                    "risk_factors",
                    models.JSONField(default=list, help_text="List of detected risk factors"),
                ),
                ("is_new_device", models.BooleanField(default=False)),
                ("is_new_location", models.BooleanField(default=False)),
                ("is_unusual_time", models.BooleanField(default=False)),
                ("failed_attempts_24h", models.IntegerField(default=0)),
                ("mfa_required", models.BooleanField(default=False)),
                ("login_blocked", models.BooleanField(default=False)),
                ("additional_verification_required", models.BooleanField(default=False)),
                ("login_successful", models.BooleanField(null=True)),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_risk_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mfa_login_risk_assessments",
                "ordering": ["-assessed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-assessed_at"], name="mfa_login_r_user_id_94d46a_idx"
                    ),
                    models.Index(fields=["ip_address"], name="mfa_login_r_ip_addr_4f343f_idx"),
                    models.Index(fields=["risk_level"], name="mfa_login_r_risk_le_d02d10_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True, help_text="Unique device fingerprint hash", max_length=64
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text='User-friendly device name (e.g., "Chrome on Windows")',
                        max_length=255,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop"),
                            ("laptop", "Laptop"),
                            ("mobile", "Mobile"),
                            ("tablet", "Tablet"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Approximate location based on IP", max_length=255
                    ),
                ),
                ("trusted_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(auto_now=True)),
                ("is_revoked", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trusted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mfa_trusted_devices",
                "ordering": ["-last_used_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_used_at"], name="mfa_trusted_user_id_005359_idx"
                    ),
                    models.Index(fields=["device_id"], name="mfa_trusted_device__add53d_idx"),
                    models.Index(fields=["expires_at"], name="mfa_trusted_expires_6f2c0d_idx"),
                ],
                "unique_together": {("user", "device_id")},
            },
        ),
    ]
