# Generated by Django 5.2.8 on 2025-12-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_add_organization_settings"),
        ("users", "0016_department_settings_and_cross_access"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["display_order", "code"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.RenameIndex(
            model_name="crossdepartmentaccess",
            new_name="cross_depar_user_id_9f534a_idx",
            old_name="cda_user_active_idx",
        ),
        migrations.RenameIndex(
            model_name="crossdepartmentaccess",
            new_name="cross_depar_departm_51a263_idx",
            old_name="cda_dept_active_idx",
        ),
        migrations.RenameIndex(
            model_name="crossdepartmentaccess",
            new_name="cross_depar_expires_670bdb_idx",
            old_name="cda_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="crossdepartmentaccess",
            new_name="cross_depar_granted_309a8b_idx",
            old_name="cda_granted_idx",
        ),
        migrations.RenameIndex(
            model_name="department",
            new_name="departments_organiz_47d68a_idx",
            old_name="dept_org_active_idx",
        ),
        migrations.RenameIndex(
            model_name="departmentaccessrequest",
            new_name="department__request_47c8bf_idx",
            old_name="dar_requester_status_idx",
        ),
        migrations.RenameIndex(
            model_name="departmentaccessrequest",
            new_name="department__departm_8d1646_idx",
            old_name="dar_dept_status_idx",
        ),
        migrations.RenameIndex(
            model_name="departmentaccessrequest",
            new_name="department__status_dd5772_idx",
            old_name="dar_status_created_idx",
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["display_order"], name="departments_display_4cbfe7_idx"),
        ),
    ]
