# Generated by Django 5.2.8 on 2025-12-04 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_department_as_root_data_migration"),
    ]

    operations = [
        migrations.AddField(
            model_name="mfasettings",
            name="backup_codes_regenerated_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time backup codes were regenerated", null=True
            ),
        ),
        migrations.AddField(
            model_name="mfasettings",
            name="backup_codes_regenerated_count",
            field=models.IntegerField(
                default=0,
                help_text="Number of times backup codes have been regenerated in the current period",
            ),
        ),
        migrations.AddField(
            model_name="mfasettings",
            name="backup_codes_regeneration_reset_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the regeneration counter was last reset (24h window start)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="crossdepartmentaccess",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cross_department_access_granted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
