# Generated by Django 5.2.8 on 2025-11-18 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0005_document_pdf_version_path_document_thumbnail_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the classification rule", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this rule does and when it applies",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Execution priority (higher values execute first). Use to control rule order.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this rule is currently active and should be applied",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text="\n        Conditions that must be met for rule to apply. Structure:\n        {\n            'filename_contains': ['keyword1', 'keyword2'],  # Any keyword in filename\n            'content_contains': ['text1', 'text2'],  # Any keyword in extracted text\n            'file_type': 'application/pdf',  # Exact MIME type match\n            'document_type': 'UNCLASSIFIED',  # Current document type\n            'min_file_size_mb': 5.0,  # Minimum file size in MB\n            'max_file_size_mb': 100.0,  # Maximum file size in MB\n            'department_id': 5  # Specific department\n        }\n        All specified conditions must match (AND logic).\n        ",
                    ),
                ),
                (
                    "actions",
                    models.JSONField(
                        default=dict,
                        help_text="\n        Actions to apply when conditions match. Structure:\n        {\n            'move_to_folder': '<folder_uuid>',  # Move to specific folder\n            'set_document_type': 'INVOICE',  # Set document type\n            'add_tags': ['finance', 'urgent'],  # Add these tags\n            'set_confidentiality': 'CONFIDENTIAL',  # Set confidentiality level\n            'assign_to_department': 5  # Assign to department ID\n        }\n        ",
                    ),
                ),
                (
                    "applied_count",
                    models.IntegerField(
                        default=0, help_text="Number of times this rule has been applied"
                    ),
                ),
                (
                    "last_applied_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this rule was successfully applied",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_classification_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_classification_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification Rule",
                "verbose_name_plural": "Classification Rules",
                "db_table": "classification_rules",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conditions_matched",
                    models.JSONField(
                        help_text="Which conditions were matched for this application"
                    ),
                ),
                (
                    "actions_applied",
                    models.JSONField(help_text="Which actions were successfully applied"),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the rule application was successful"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if application failed"),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        default="auto",
                        help_text="How this classification was triggered (auto, manual, bulk)",
                        max_length=50,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classification_logs",
                        to="documents.document",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_logs",
                        to="classification.classificationrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification Log",
                "verbose_name_plural": "Classification Logs",
                "db_table": "classification_logs",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.AddIndex(
            model_name="classificationrule",
            index=models.Index(
                fields=["is_active", "-priority"], name="classificat_is_acti_4315b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationrule",
            index=models.Index(fields=["created_at"], name="classificat_created_b7b03a_idx"),
        ),
        migrations.AddIndex(
            model_name="classificationlog",
            index=models.Index(
                fields=["document", "-applied_at"], name="classificat_documen_349e61_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationlog",
            index=models.Index(
                fields=["rule", "-applied_at"], name="classificat_rule_id_0dc499_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationlog",
            index=models.Index(fields=["applied_at"], name="classificat_applied_df68bb_idx"),
        ),
    ]
