# Generated by Django 5.2.8 on 2025-11-28 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classification", "0001_initial"),
        ("documents", "0015_document_states"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "high_confidence_threshold",
                    models.FloatField(
                        default=0.95, help_text="Threshold for auto-apply (default: 0.95 = 95%)"
                    ),
                ),
                (
                    "medium_confidence_threshold",
                    models.FloatField(
                        default=0.85, help_text="Threshold for suggestion (default: 0.85 = 85%)"
                    ),
                ),
                (
                    "auto_apply_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether to auto-apply high confidence predictions"
                    ),
                ),
                (
                    "auto_apply_document_type",
                    models.BooleanField(
                        default=True, help_text="Auto-apply document type classification"
                    ),
                ),
                (
                    "auto_apply_confidentiality",
                    models.BooleanField(
                        default=False,
                        help_text="Auto-apply confidentiality classification (more sensitive)",
                    ),
                ),
                (
                    "auto_apply_department",
                    models.BooleanField(
                        default=False, help_text="Auto-apply department assignment"
                    ),
                ),
                (
                    "auto_retrain_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether to automatically retrain models"
                    ),
                ),
                (
                    "retrain_threshold",
                    models.IntegerField(
                        default=100,
                        help_text="Minimum new feedback items before triggering retrain",
                    ),
                ),
                (
                    "retrain_schedule",
                    models.CharField(
                        default="weekly",
                        help_text="Retraining schedule (daily, weekly, monthly)",
                        max_length=50,
                    ),
                ),
                (
                    "min_training_samples",
                    models.IntegerField(
                        default=50, help_text="Minimum samples required to train a model"
                    ),
                ),
                (
                    "notify_on_low_confidence",
                    models.BooleanField(
                        default=True, help_text="Send notifications for low confidence predictions"
                    ),
                ),
                (
                    "notify_on_model_retrain",
                    models.BooleanField(
                        default=True, help_text="Send notifications when models are retrained"
                    ),
                ),
                (
                    "max_text_length",
                    models.IntegerField(
                        default=10000,
                        help_text="Maximum characters of text to use for classification",
                    ),
                ),
                (
                    "include_filename",
                    models.BooleanField(default=True, help_text="Include filename in features"),
                ),
                (
                    "include_file_type",
                    models.BooleanField(default=True, help_text="Include file type in features"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_classification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification Settings",
                "verbose_name_plural": "Classification Settings",
                "db_table": "classification_settings",
            },
        ),
        migrations.CreateModel(
            name="MLClassificationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Descriptive name for the model", max_length=200),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("document_type", "Document Type"),
                            ("confidentiality", "Confidentiality Level"),
                            ("department", "Department"),
                            ("custom", "Custom Classification"),
                        ],
                        default="document_type",
                        help_text="What this model classifies",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Model version (e.g., 1.0.0, 2024-11-29)", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("ready", "Ready"),
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("failed", "Failed"),
                        ],
                        default="training",
                        help_text="Current status of the model",
                        max_length=20,
                    ),
                ),
                (
                    "model_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the serialized model file (.pkl)",
                        max_length=500,
                    ),
                ),
                (
                    "vectorizer_file_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the serialized vectorizer file (.pkl)",
                        max_length=500,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        default="multinomial_nb",
                        help_text="ML algorithm used (e.g., multinomial_nb, random_forest, svm)",
                        max_length=100,
                    ),
                ),
                (
                    "hyperparameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Model hyperparameters used during training",
                    ),
                ),
                (
                    "feature_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="\n        Feature extraction configuration:\n        {\n            'use_filename': True,\n            'use_content': True,\n            'use_file_type': True,\n            'max_features': 5000,\n            'ngram_range': [1, 2]\n        }\n        ",
                    ),
                ),
                (
                    "training_samples",
                    models.IntegerField(default=0, help_text="Number of samples used for training"),
                ),
                (
                    "training_classes",
                    models.JSONField(
                        default=list, help_text="List of classes the model can predict"
                    ),
                ),
                (
                    "training_started_at",
                    models.DateTimeField(blank=True, help_text="When training started", null=True),
                ),
                (
                    "training_completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When training completed", null=True
                    ),
                ),
                (
                    "training_duration_seconds",
                    models.FloatField(
                        blank=True, help_text="Training duration in seconds", null=True
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="Model accuracy on test set (0.0 - 1.0)", null=True
                    ),
                ),
                (
                    "precision",
                    models.FloatField(
                        blank=True, help_text="Model precision (weighted average)", null=True
                    ),
                ),
                (
                    "recall",
                    models.FloatField(
                        blank=True, help_text="Model recall (weighted average)", null=True
                    ),
                ),
                (
                    "f1_score",
                    models.FloatField(
                        blank=True, help_text="Model F1 score (weighted average)", null=True
                    ),
                ),
                (
                    "confusion_matrix",
                    models.JSONField(
                        blank=True, default=dict, help_text="Confusion matrix as JSON"
                    ),
                ),
                (
                    "classification_report",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed classification report per class",
                    ),
                ),
                (
                    "predictions_count",
                    models.IntegerField(
                        default=0, help_text="Total predictions made with this model"
                    ),
                ),
                (
                    "correct_predictions",
                    models.IntegerField(
                        default=0, help_text="Predictions confirmed as correct by users"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="Last time this model made a prediction", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_ml_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Classification Model",
                "verbose_name_plural": "ML Classification Models",
                "db_table": "ml_classification_models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClassificationPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "predicted_class",
                    models.CharField(help_text="The predicted classification", max_length=100),
                ),
                ("confidence_score", models.FloatField(help_text="Confidence score (0.0 - 1.0)")),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("high", "High (Auto-apply)"),
                            ("medium", "Medium (Suggest)"),
                            ("low", "Low (Manual required)"),
                        ],
                        help_text="Confidence tier for routing",
                        max_length=20,
                    ),
                ),
                (
                    "class_probabilities",
                    models.JSONField(
                        default=dict, help_text="Probability distribution across all classes"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("auto_applied", "Auto Applied"),
                            ("confirmed", "User Confirmed"),
                            ("corrected", "User Corrected"),
                            ("rejected", "User Rejected"),
                        ],
                        default="pending",
                        help_text="Current review status",
                        max_length=20,
                    ),
                ),
                (
                    "user_correction",
                    models.CharField(
                        blank=True,
                        help_text="The correct class if user corrected the prediction",
                        max_length=100,
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the prediction was reviewed", null=True
                    ),
                ),
                (
                    "actions_applied",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Actions that were applied based on this prediction",
                    ),
                ),
                (
                    "feature_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of features used for this prediction",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_predictions",
                        to="documents.document",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predictions",
                        to="classification.mlclassificationmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classification Prediction",
                "verbose_name_plural": "Classification Predictions",
                "db_table": "classification_predictions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "classification_target",
                    models.CharField(
                        default="document_type",
                        help_text="Which field this feedback is for (document_type, confidentiality, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "original_prediction",
                    models.CharField(
                        blank=True,
                        help_text="What the model predicted (if applicable)",
                        max_length=100,
                    ),
                ),
                (
                    "corrected_class",
                    models.CharField(help_text="The correct classification", max_length=100),
                ),
                (
                    "feedback_source",
                    models.CharField(
                        choices=[
                            ("user_correction", "User Correction"),
                            ("manual_classification", "Manual Classification"),
                            ("batch_labeling", "Batch Labeling"),
                            ("rule_based", "From Rule-Based System"),
                        ],
                        default="user_correction",
                        max_length=30,
                    ),
                ),
                (
                    "feature_text",
                    models.TextField(
                        blank=True, help_text="Combined text features used for training"
                    ),
                ),
                (
                    "used_in_training",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this feedback has been used in model retraining",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_feedback",
                        to="documents.document",
                    ),
                ),
                (
                    "prediction",
                    models.ForeignKey(
                        blank=True,
                        help_text="The prediction that was corrected (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to="classification.classificationprediction",
                    ),
                ),
                (
                    "provided_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="provided_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trained_model",
                    models.ForeignKey(
                        blank=True,
                        help_text="The model that was trained with this feedback",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_feedback_used",
                        to="classification.mlclassificationmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Feedback",
                "verbose_name_plural": "Training Feedback",
                "db_table": "training_feedback",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="mlclassificationmodel",
            index=models.Index(
                fields=["model_type", "status"], name="ml_classifi_model_t_fa2b7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mlclassificationmodel",
            index=models.Index(
                fields=["status", "-created_at"], name="ml_classifi_status_ad06cd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mlclassificationmodel",
            unique_together={("model_type", "version")},
        ),
        migrations.AddIndex(
            model_name="classificationprediction",
            index=models.Index(
                fields=["review_status", "-created_at"], name="classificat_review__f6f17a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationprediction",
            index=models.Index(
                fields=["confidence_level", "-created_at"], name="classificat_confide_f977cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationprediction",
            index=models.Index(
                fields=["document", "-created_at"], name="classificat_documen_1ca305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="classificationprediction",
            index=models.Index(
                fields=["model", "-created_at"], name="classificat_model_i_2ec425_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingfeedback",
            index=models.Index(
                fields=["used_in_training", "-created_at"], name="training_fe_used_in_e635f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingfeedback",
            index=models.Index(
                fields=["classification_target", "-created_at"],
                name="training_fe_classif_a1a828_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trainingfeedback",
            index=models.Index(fields=["corrected_class"], name="training_fe_correct_56543f_idx"),
        ),
    ]
