# Generated by Django 5.2.8 on 2026-03-09 21:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0005_add_organization_settings"),
        ("users", "0019_add_backup_code_regeneration_tracking"),
        ("workflows", "0006_remove_workflowinstance_workflow_in_documen_8a323d_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("multi_select", "Multi Select"),
                            ("true_false", "True/False"),
                            ("short_answer", "Short Answer"),
                            ("ordering", "Ordering"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField()),
                ("points", models.PositiveIntegerField(default=1)),
                ("is_mandatory", models.BooleanField(default=False)),
                ("auto_grade_keywords", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "procedure_quiz_questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="VersionQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_question_id", models.UUIDField()),
                ("question_type", models.CharField(max_length=20)),
                ("text", models.TextField()),
                ("explanation", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField()),
                ("points", models.PositiveIntegerField()),
                ("is_mandatory", models.BooleanField()),
                ("auto_grade_keywords", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "version_quiz_questions",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Procedure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("current_version", models.PositiveIntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_procedures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="users.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedures",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent_procedure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="procedures.procedure",
                    ),
                ),
            ],
            options={
                "db_table": "procedures",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "assignment_source",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Assignment"),
                            ("department", "Department Assignment"),
                            ("role", "Role Assignment"),
                            ("recertification", "Auto Re-certification"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completion_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                ("reminder_count", models.PositiveIntegerField(default=0)),
                ("waiver_reason", models.TextField(blank=True)),
                ("waived_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_assignments",
                        to="organizations.organization",
                    ),
                ),
                (
                    "waived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "procedure_assignments",
                "ordering": ["-assigned_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField()),
                ("estimated_duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("branch_condition", models.JSONField(blank=True, null=True)),
                ("require_manual_open", models.BooleanField(default=False)),
                ("require_media_completion", models.BooleanField(default=False)),
                ("require_quiz_pass", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="procedures.procedure",
                    ),
                ),
            ],
            options={
                "db_table": "procedure_steps",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureStepComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("body", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="procedures.procedurestepcomment",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_comments",
                        to="procedures.procedurestep",
                    ),
                ),
                (
                    "workflow_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedure_step_comments",
                        to="workflows.workflowinstance",
                    ),
                ),
            ],
            options={
                "db_table": "procedure_step_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("tags", models.JSONField(default=list)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("effective_from", models.DateField()),
                ("expires_on", models.DateField()),
                ("approval_comment", models.TextField(blank=True)),
                ("changelog", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("retirement_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="procedures.procedure",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "procedure_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="ProcedureAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("submitted_for_review", "Submitted for Review"),
                            ("review_approved", "Review Approved"),
                            ("review_rejected", "Review Rejected"),
                            ("published", "Published"),
                            ("retired", "Retired"),
                            ("deleted", "Deleted"),
                            ("step_added", "Step Added"),
                            ("step_updated", "Step Updated"),
                            ("step_deleted", "Step Deleted"),
                            ("step_reordered", "Steps Reordered"),
                            ("attachment_uploaded", "Attachment Uploaded"),
                            ("attachment_deleted", "Attachment Deleted"),
                            ("quiz_created", "Quiz Created"),
                            ("quiz_updated", "Quiz Updated"),
                            ("quiz_deleted", "Quiz Deleted"),
                            ("review_comment_added", "Review Comment Added"),
                            ("review_comment_resolved", "Review Comment Resolved"),
                            ("assigned", "Assigned"),
                            ("assignment_waived", "Assignment Waived"),
                            ("training_started", "Training Started"),
                            ("training_completed", "Training Completed"),
                            ("training_failed", "Training Failed"),
                            ("step_completed", "Step Completed"),
                            ("quiz_attempted", "Quiz Attempted"),
                            ("quiz_passed", "Quiz Passed"),
                            ("quiz_failed", "Quiz Failed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("step_id", models.UUIDField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("detail", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="procedures.procedureassignment",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "procedure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="procedures.procedure",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="procedures.procedureversion",
                    ),
                ),
            ],
            options={
                "db_table": "procedure_audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddField(
            model_name="procedureassignment",
            name="procedure_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="procedures.procedureversion",
            ),
        ),
        migrations.CreateModel(
            name="ProcedureVersionStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_step_id", models.UUIDField()),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField()),
                ("estimated_duration_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("branch_condition", models.JSONField(blank=True, null=True)),
                ("require_manual_open", models.BooleanField(default=False)),
                ("require_media_completion", models.BooleanField(default=False)),
                ("require_quiz_pass", models.BooleanField(default=False)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="procedures.procedureversion",
                    ),
                ),
            ],
            options={
                "db_table": "procedure_version_steps",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("correct_order", models.PositiveIntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="procedures.question",
                    ),
                ),
            ],
            options={
                "db_table": "procedure_answer_options",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "quiz_type",
                    models.CharField(
                        choices=[
                            ("step_level", "Step Level"),
                            ("end_of_procedure", "End of Procedure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("passing_score_percent", models.PositiveIntegerField(default=80)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("time_limit_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("shuffle_questions", models.BooleanField(default=False)),
                ("shuffle_answers", models.BooleanField(default=False)),
                ("show_correct_answers_after", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "procedure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="procedures.procedure",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="procedures.procedurestep",
                    ),
                ),
            ],
            options={
                "db_table": "procedure_quizzes",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="procedures.quiz",
            ),
        ),
        migrations.CreateModel(
            name="StepAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("template", "Template"),
                            ("reference", "Reference Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="procedures/attachments/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField()),
                ("file_extension", models.CharField(max_length=10)),
                ("mime_type", models.CharField(max_length=100)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("order", models.PositiveIntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="procedures.procedurestep",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "procedure_step_attachments",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("steps_completed", models.PositiveIntegerField(default=0)),
                ("total_steps", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_time_seconds", models.PositiveIntegerField(default=0)),
                (
                    "total_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("passed_all_mandatory", models.BooleanField(default=False)),
                ("trainee_context", models.JSONField(default=dict)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="procedures.procedureassignment",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="procedures.procedureversionstep",
                    ),
                ),
            ],
            options={
                "db_table": "training_attempts",
                "ordering": ["attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="StepCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("started", "Started"),
                            ("viewed", "Viewed"),
                            ("manual_opened", "Manual Opened"),
                            ("media_completed", "Media Completed"),
                            ("quiz_passed", "Quiz Passed"),
                            ("quiz_failed", "Quiz Failed"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("manual_opened_at", models.DateTimeField(blank=True, null=True)),
                ("media_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "version_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="procedures.procedureversionstep",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_completions",
                        to="procedures.trainingattempt",
                    ),
                ),
            ],
            options={
                "db_table": "step_completions",
                "ordering": ["version_step__order"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("score_earned", models.PositiveIntegerField(default=0)),
                ("score_possible", models.PositiveIntegerField(default=0)),
                (
                    "score_percent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("passed", models.BooleanField(default=False)),
                ("passed_all_mandatory", models.BooleanField(default=False)),
                (
                    "training_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to="procedures.trainingattempt",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_attempts",
                "ordering": ["attempt_number"],
            },
        ),
        migrations.CreateModel(
            name="VersionAnswerOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_option_id", models.UUIDField()),
                ("text", models.TextField()),
                ("is_correct", models.BooleanField()),
                ("correct_order", models.PositiveIntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "version_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="procedures.versionquestion",
                    ),
                ),
            ],
            options={
                "db_table": "version_answer_options",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("text_response", models.TextField(blank=True)),
                ("submitted_order", models.JSONField(blank=True, null=True)),
                ("is_correct", models.BooleanField(null=True)),
                ("points_earned", models.PositiveIntegerField(default=0)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="procedures.quizattempt",
                    ),
                ),
                (
                    "selected_options",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="procedures.versionansweroption"
                    ),
                ),
                (
                    "version_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="procedures.versionquestion",
                    ),
                ),
            ],
            options={
                "db_table": "question_responses",
            },
        ),
        migrations.CreateModel(
            name="VersionQuiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_quiz_id", models.UUIDField()),
                ("quiz_type", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("passing_score_percent", models.PositiveIntegerField()),
                ("max_attempts", models.PositiveIntegerField()),
                ("time_limit_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("shuffle_questions", models.BooleanField()),
                ("shuffle_answers", models.BooleanField()),
                ("show_correct_answers_after", models.BooleanField()),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="procedures.procedureversion",
                    ),
                ),
                (
                    "version_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="procedures.procedureversionstep",
                    ),
                ),
            ],
            options={
                "db_table": "version_quizzes",
            },
        ),
        migrations.AddField(
            model_name="versionquestion",
            name="version_quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="procedures.versionquiz",
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="version_quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="procedures.versionquiz",
            ),
        ),
        migrations.CreateModel(
            name="VersionStepAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("original_attachment_id", models.UUIDField()),
                ("attachment_type", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveBigIntegerField()),
                ("file_extension", models.CharField(max_length=10)),
                ("mime_type", models.CharField(max_length=100)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "version_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="procedures.procedureversionstep",
                    ),
                ),
            ],
            options={
                "db_table": "version_step_attachments",
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="procedure",
            index=models.Index(
                fields=["organization", "state"], name="procedures_organiz_beae4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procedure",
            index=models.Index(fields=["department"], name="procedures_departm_e1a14e_idx"),
        ),
        migrations.AddIndex(
            model_name="procedure",
            index=models.Index(fields=["created_by"], name="procedures_created_4f6f4d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="procedurestep",
            unique_together={("procedure", "order")},
        ),
        migrations.AddIndex(
            model_name="procedurestepcomment",
            index=models.Index(
                fields=["workflow_instance", "step"], name="procedure_s_workflo_2c1751_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="procedureversion",
            unique_together={("procedure", "version_number")},
        ),
        migrations.AddIndex(
            model_name="procedureauditlog",
            index=models.Index(
                fields=["organization", "action"], name="procedure_a_organiz_1f635d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procedureauditlog",
            index=models.Index(
                fields=["procedure", "-timestamp"], name="procedure_a_procedu_d4a418_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procedureauditlog",
            index=models.Index(
                fields=["actor", "-timestamp"], name="procedure_a_actor_i_d59f57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procedureassignment",
            index=models.Index(
                fields=["assignee", "status"], name="procedure_a_assigne_f05e5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="procedureassignment",
            index=models.Index(fields=["due_date"], name="procedure_a_due_dat_d45a87_idx"),
        ),
        migrations.AddIndex(
            model_name="procedureassignment",
            index=models.Index(
                fields=["organization", "status"], name="procedure_a_organiz_93f0b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("quiz_type", "step_level"), ("step__isnull", False)),
                    models.Q(("quiz_type", "end_of_procedure"), ("step__isnull", True)),
                    _connector="OR",
                ),
                name="quiz_step_consistency",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trainingattempt",
            unique_together={("assignment", "attempt_number")},
        ),
        migrations.AlterUniqueTogether(
            name="stepcompletion",
            unique_together={("attempt", "version_step")},
        ),
    ]
