# Generated by Django 5.2.8 on 2026-03-10 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0017_add_deleted_by_field"),
        ("procedures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepattachment",
            name="document_reference",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this attachment links to an existing document (file field will be blank).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="step_attachment_links",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="versionstepattachment",
            name="document_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documents.document",
            ),
        ),
        migrations.AlterField(
            model_name="stepattachment",
            name="checksum_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="stepattachment",
            name="file",
            field=models.FileField(blank=True, upload_to="procedures/attachments/%Y/%m/"),
        ),
        migrations.AlterField(
            model_name="stepattachment",
            name="file_extension",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="stepattachment",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="stepattachment",
            name="file_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stepattachment",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="versionstepattachment",
            name="checksum_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="versionstepattachment",
            name="file",
            field=models.FileField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="versionstepattachment",
            name="file_extension",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="versionstepattachment",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="versionstepattachment",
            name="file_size",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="versionstepattachment",
            name="mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
