# Generated by Django 5.2.8 on 2026-03-10 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0002_stepattachment_document_reference_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurestep",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("changes_requested", "Changes Requested"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="procedurestep",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned to review this specific step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_step_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
