# Generated by Django 5.2.8 on 2026-03-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0003_add_step_reviewer_and_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurestep",
            name="example_scenarios",
            field=models.TextField(
                blank=True, help_text="Practical examples or scenarios illustrating this step."
            ),
        ),
        migrations.AddField(
            model_name="procedurestep",
            name="key_concepts",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of strings — core ideas the trainee must understand.",
            ),
        ),
        migrations.AddField(
            model_name="procedurestep",
            name="learning_objectives",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of strings — what the trainee should learn from this step.",
            ),
        ),
        migrations.AddField(
            model_name="procedureversionstep",
            name="example_scenarios",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="procedureversionstep",
            name="key_concepts",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="procedureversionstep",
            name="learning_objectives",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
