# Generated by Django 5.2.8 on 2026-03-12 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0004_structured_learning_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurestep",
            name="step_owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Subject-matter expert assigned to author/edit this step.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_procedure_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
