# Generated by Django 5.2.8 on 2026-03-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0005_step_owner_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedureauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("submitted_for_review", "Submitted for Review"),
                    ("review_approved", "Review Approved"),
                    ("review_rejected", "Review Rejected"),
                    ("published", "Published"),
                    ("retired", "Retired"),
                    ("reverted_to_draft", "Reverted to Draft"),
                    ("deleted", "Deleted"),
                    ("step_added", "Step Added"),
                    ("step_updated", "Step Updated"),
                    ("step_deleted", "Step Deleted"),
                    ("step_reordered", "Steps Reordered"),
                    ("attachment_uploaded", "Attachment Uploaded"),
                    ("attachment_deleted", "Attachment Deleted"),
                    ("quiz_created", "Quiz Created"),
                    ("quiz_updated", "Quiz Updated"),
                    ("quiz_deleted", "Quiz Deleted"),
                    ("review_comment_added", "Review Comment Added"),
                    ("review_comment_resolved", "Review Comment Resolved"),
                    ("assigned", "Assigned"),
                    ("assignment_waived", "Assignment Waived"),
                    ("training_started", "Training Started"),
                    ("training_completed", "Training Completed"),
                    ("training_failed", "Training Failed"),
                    ("step_completed", "Step Completed"),
                    ("quiz_attempted", "Quiz Attempted"),
                    ("quiz_passed", "Quiz Passed"),
                    ("quiz_failed", "Quiz Failed"),
                ],
                max_length=30,
            ),
        ),
    ]
