# Generated by Django 5.2.8 on 2026-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0006_alter_procedureauditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurestep",
            name="video_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL to an embedded video (YouTube, Vimeo, etc.)",
                max_length=2000,
            ),
        ),
        migrations.AddField(
            model_name="procedureversionstep",
            name="video_url",
            field=models.URLField(blank=True, default="", max_length=2000),
        ),
    ]
