# Generated by Django 5.2.8 on 2026-03-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0007_procedurestep_video_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedureassignment",
            name="max_training_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
