# Generated by Django 5.2.8 on 2026-03-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0008_add_max_training_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="procedurestep",
            name="require_read_content",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="procedureversionstep",
            name="require_read_content",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stepcompletion",
            name="content_read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
