# Generated by Django 5.2.8 on 2026-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procedures", "0009_add_require_read_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="stepattachment",
            name="extracted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stepattachment",
            name="extracted_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="stepattachment",
            name="extraction_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="stepattachment",
            name="extraction_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("unsupported", "Unsupported file type"),
                    ("no_text", "No extractable text (likely scanned)"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="versionstepattachment",
            name="extracted_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="versionstepattachment",
            name="extraction_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
