# Generated by Django 5.2.8 on 2025-11-29 04:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0015_document_states"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntelligenceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "enable_entity_extraction",
                    models.BooleanField(default=True, help_text="Enable named entity recognition"),
                ),
                (
                    "entity_confidence_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Minimum confidence for entity extraction",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "entity_types_enabled",
                    models.JSONField(default=list, help_text="List of enabled entity types"),
                ),
                (
                    "enable_table_extraction",
                    models.BooleanField(
                        default=True, help_text="Enable table detection and extraction"
                    ),
                ),
                (
                    "table_extraction_method",
                    models.CharField(
                        default="auto",
                        help_text="Table extraction method (auto, camelot, tabula, custom)",
                        max_length=50,
                    ),
                ),
                (
                    "enable_summarization",
                    models.BooleanField(default=True, help_text="Enable document summarization"),
                ),
                (
                    "default_summary_type",
                    models.CharField(
                        default="STANDARD",
                        help_text="Default summary type to generate",
                        max_length=20,
                    ),
                ),
                (
                    "max_summary_length",
                    models.IntegerField(default=500, help_text="Maximum summary length in words"),
                ),
                (
                    "enable_key_value_extraction",
                    models.BooleanField(default=True, help_text="Enable key-value pair extraction"),
                ),
                (
                    "key_value_templates",
                    models.JSONField(
                        default=dict,
                        help_text="Templates for common document types (invoice, contract, etc.)",
                    ),
                ),
                (
                    "auto_process_on_upload",
                    models.BooleanField(
                        default=False, help_text="Automatically process documents on upload"
                    ),
                ),
                (
                    "process_document_types",
                    models.JSONField(default=list, help_text="Document types to auto-process"),
                ),
                (
                    "max_file_size_mb",
                    models.IntegerField(
                        default=50, help_text="Maximum file size for processing (MB)"
                    ),
                ),
                (
                    "max_pages",
                    models.IntegerField(
                        default=100, help_text="Maximum pages to process per document"
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=10, help_text="Number of documents to process in batch"
                    ),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(default=300, help_text="Processing timeout per document"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_intelligence_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Intelligence Settings",
                "verbose_name_plural": "Intelligence Settings",
                "db_table": "intelligence_settings",
            },
        ),
        migrations.CreateModel(
            name="DocumentSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[
                            ("BRIEF", "Brief (1-2 sentences)"),
                            ("STANDARD", "Standard Summary"),
                            ("DETAILED", "Detailed Summary"),
                            ("BULLET_POINTS", "Bullet Points"),
                            ("EXECUTIVE", "Executive Summary"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("summary_text", models.TextField(help_text="The generated summary")),
                (
                    "key_points",
                    models.JSONField(default=list, help_text="List of key points/takeaways"),
                ),
                (
                    "topics",
                    models.JSONField(default=list, help_text="Main topics identified in document"),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        help_text="Overall sentiment (positive, negative, neutral)",
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="Sentiment score (-1.0 to 1.0)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        default="extractive",
                        help_text="Model/method used for summarization",
                        max_length=100,
                    ),
                ),
                ("word_count", models.IntegerField(default=0, help_text="Word count of summary")),
                (
                    "compression_ratio",
                    models.FloatField(
                        blank=True, help_text="Ratio of summary length to original", null=True
                    ),
                ),
                (
                    "coherence_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "relevance_score",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "user_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="User rating (1-5 stars)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("user_feedback", models.TextField(blank=True, help_text="Optional user feedback")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="documents.document",
                    ),
                ),
                (
                    "rated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rated_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Summary",
                "verbose_name_plural": "Document Summaries",
                "db_table": "document_summaries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "summary_type"], name="document_su_documen_0d5f05_idx"
                    ),
                    models.Index(
                        fields=["summary_type", "-created_at"],
                        name="document_su_summary_8c5db5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExtractedEntity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("PERSON", "Person"),
                            ("ORGANIZATION", "Organization"),
                            ("DATE", "Date"),
                            ("MONEY", "Money"),
                            ("PERCENTAGE", "Percentage"),
                            ("LOCATION", "Location"),
                            ("PHONE", "Phone Number"),
                            ("EMAIL", "Email Address"),
                            ("ACCOUNT_NUMBER", "Account Number"),
                            ("REFERENCE", "Reference Number"),
                            ("CUSTOM", "Custom"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        help_text='The extracted entity value (e.g., "John Smith", "$5,000")'
                    ),
                ),
                (
                    "normalized_value",
                    models.TextField(
                        blank=True,
                        help_text='Normalized/standardized value (e.g., "5000.00" for money)',
                    ),
                ),
                (
                    "start_position",
                    models.IntegerField(
                        blank=True,
                        help_text="Character start position in extracted text",
                        null=True,
                    ),
                ),
                (
                    "end_position",
                    models.IntegerField(
                        blank=True, help_text="Character end position in extracted text", null=True
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Page number where entity was found (1-indexed)",
                        null=True,
                    ),
                ),
                ("context", models.TextField(blank=True, help_text="Surrounding text for context")),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Extraction confidence (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        default="nlp",
                        help_text="Method used for extraction (nlp, regex, ml)",
                        max_length=50,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether entity has been verified by a user"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_entities",
                        to="documents.document",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_entities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted Entity",
                "verbose_name_plural": "Extracted Entities",
                "db_table": "extracted_entities",
                "ordering": ["document", "start_position"],
                "indexes": [
                    models.Index(
                        fields=["document", "entity_type"], name="extracted_e_documen_ba44eb_idx"
                    ),
                    models.Index(
                        fields=["entity_type", "value"], name="extracted_e_entity__ae5555_idx"
                    ),
                    models.Index(
                        fields=["document", "-confidence_score"],
                        name="extracted_e_documen_9ea26f_idx",
                    ),
                    models.Index(fields=["is_verified"], name="extracted_e_is_veri_0f8a34_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExtractedKeyValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(help_text="The field name/label", max_length=255)),
                ("value", models.TextField(help_text="The extracted value")),
                (
                    "normalized_key",
                    models.CharField(
                        blank=True,
                        help_text='Standardized key name (e.g., "invoice_number")',
                        max_length=255,
                    ),
                ),
                (
                    "normalized_value",
                    models.TextField(blank=True, help_text="Normalized/parsed value"),
                ),
                (
                    "value_type",
                    models.CharField(
                        default="text",
                        help_text="Data type (text, number, date, currency, boolean)",
                        max_length=50,
                    ),
                ),
                ("page_number", models.IntegerField(blank=True, null=True)),
                (
                    "confidence_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True,
                        help_text='Group name for related fields (e.g., "billing_address")',
                        max_length=100,
                    ),
                ),
                ("group_order", models.IntegerField(default=0, help_text="Order within group")),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_key_values",
                        to="documents.document",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_key_values",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted Key-Value",
                "verbose_name_plural": "Extracted Key-Values",
                "db_table": "extracted_key_values",
                "ordering": ["document", "group_name", "group_order"],
                "indexes": [
                    models.Index(
                        fields=["document", "normalized_key"], name="extracted_k_documen_204156_idx"
                    ),
                    models.Index(
                        fields=["normalized_key", "value"], name="extracted_k_normali_7a7752_idx"
                    ),
                    models.Index(
                        fields=["document", "group_name"], name="extracted_k_documen_27c27a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExtractedTable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "table_number",
                    models.IntegerField(help_text="Table number in document (1-indexed)"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Table title/caption if detected", max_length=500
                    ),
                ),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True, help_text="Page number where table starts", null=True
                    ),
                ),
                ("headers", models.JSONField(default=list, help_text="List of column headers")),
                (
                    "rows",
                    models.JSONField(
                        default=list,
                        help_text="List of row data (each row is a list of cell values)",
                    ),
                ),
                (
                    "row_count",
                    models.IntegerField(
                        default=0, help_text="Number of data rows (excluding header)"
                    ),
                ),
                ("column_count", models.IntegerField(default=0, help_text="Number of columns")),
                (
                    "table_type",
                    models.CharField(
                        default="generic",
                        help_text="Detected table type (financial, schedule, contacts, generic)",
                        max_length=50,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Extraction confidence (0.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "raw_html",
                    models.TextField(blank=True, help_text="Raw HTML representation of table"),
                ),
                (
                    "raw_markdown",
                    models.TextField(blank=True, help_text="Markdown representation of table"),
                ),
                (
                    "has_merged_cells",
                    models.BooleanField(
                        default=False, help_text="Whether table contains merged cells"
                    ),
                ),
                (
                    "extraction_method",
                    models.CharField(
                        default="camelot",
                        help_text="Method used for extraction (camelot, tabula, custom)",
                        max_length=50,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_tables",
                        to="documents.document",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_tables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Extracted Table",
                "verbose_name_plural": "Extracted Tables",
                "db_table": "extracted_tables",
                "ordering": ["document", "table_number"],
                "indexes": [
                    models.Index(
                        fields=["document", "page_number"], name="extracted_t_documen_034df3_idx"
                    ),
                    models.Index(fields=["table_type"], name="extracted_t_table_t_2536d8_idx"),
                ],
                "unique_together": {("document", "table_number")},
            },
        ),
        migrations.CreateModel(
            name="IntelligenceJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Analysis"),
                            ("ENTITIES", "Entity Extraction Only"),
                            ("TABLES", "Table Extraction Only"),
                            ("SUMMARY", "Summarization Only"),
                            ("KEY_VALUES", "Key-Value Extraction Only"),
                        ],
                        default="FULL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "progress_percent",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "current_task",
                    models.CharField(
                        blank=True, help_text="Current task being processed", max_length=100
                    ),
                ),
                ("entities_found", models.IntegerField(default=0)),
                ("tables_found", models.IntegerField(default=0)),
                ("key_values_found", models.IntegerField(default=0)),
                ("summaries_generated", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Job configuration options"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intelligence_jobs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_jobs",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intelligence Job",
                "verbose_name_plural": "Intelligence Jobs",
                "db_table": "intelligence_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "-created_at"], name="intelligenc_documen_cc7eca_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="intelligenc_status_778ce8_idx"
                    ),
                    models.Index(
                        fields=["job_type", "status"], name="intelligenc_job_typ_c0c78b_idx"
                    ),
                ],
            },
        ),
    ]
