# Generated by Django 5.2.8 on 2025-11-19 01:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0006_document_account_number_document_customer_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalHold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("case_number", models.CharField(db_index=True, max_length=200, unique=True)),
                ("case_name", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "placed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placed_legal_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="released_legal_holds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Hold",
                "verbose_name_plural": "Legal Holds",
                "db_table": "legal_holds",
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalHoldDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="documents.document"
                    ),
                ),
                (
                    "legal_hold",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="retention.legalhold"
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Hold Document",
                "verbose_name_plural": "Legal Hold Documents",
                "db_table": "legal_hold_documents",
                "ordering": ["-added_at"],
                "unique_together": {("legal_hold", "document")},
            },
        ),
        migrations.AddField(
            model_name="legalhold",
            name="documents",
            field=models.ManyToManyField(
                related_name="legal_holds",
                through="retention.LegalHoldDocument",
                to="documents.document",
            ),
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT_TYPE", "Document Type Based"),
                            ("DEPARTMENT", "Department Based"),
                            ("FOLDER", "Folder Based"),
                            ("TAG", "Tag Based"),
                            ("CUSTOM", "Custom Rule"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "retention_days",
                    models.IntegerField(
                        help_text="Number of days to retain documents (e.g., 2555 = 7 years)"
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(
                        default=dict,
                        help_text='Matching criteria (e.g., {"document_type": "Invoice", "department_id": "..."})',
                    ),
                ),
                (
                    "grace_period_days",
                    models.IntegerField(
                        default=30,
                        help_text="Days to wait after retention period expires before deletion",
                    ),
                ),
                (
                    "notify_before_days",
                    models.IntegerField(
                        default=30, help_text="Notify document owner N days before deletion"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher priority policies override lower (for conflicts)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_retention_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Retention Policy",
                "verbose_name_plural": "Retention Policies",
                "db_table": "retention_policies",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="RetentionSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "retention_end_date",
                    models.DateTimeField(help_text="When retention period ends"),
                ),
                ("notification_date", models.DateTimeField(help_text="When to notify owner")),
                (
                    "deletion_date",
                    models.DateTimeField(help_text="When to delete (retention_end + grace period)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("NOTIFIED", "Notified"),
                            ("DELETED", "Deleted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notification_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_schedule",
                        to="documents.document",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="retention.retentionpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retention Schedule",
                "verbose_name_plural": "Retention Schedules",
                "db_table": "retention_schedules",
                "ordering": ["deletion_date"],
            },
        ),
        migrations.AddIndex(
            model_name="retentionpolicy",
            index=models.Index(
                fields=["-priority", "is_active"], name="retention_p_priorit_eebd9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retentionschedule",
            index=models.Index(
                fields=["status", "deletion_date"], name="retention_s_status_0643e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retentionschedule",
            index=models.Index(
                fields=["status", "notification_date"], name="retention_s_status_b49689_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retentionschedule",
            index=models.Index(
                fields=["notification_sent", "notification_date"],
                name="retention_s_notific_8bdb60_idx",
            ),
        ),
    ]
