# Generated by Django 5.2.8 on 2025-11-18 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0002_initial"),
        ("folders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("case_number", models.CharField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=500)),
                (
                    "reason",
                    models.TextField(help_text="Legal reason for placing documents on hold"),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(blank=True, help_text="NULL = indefinite hold", null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_holds_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_holds_released",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Hold",
                "verbose_name_plural": "Legal Holds",
                "db_table": "legal_holds",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "retention_period_years",
                    models.IntegerField(help_text="Number of years to retain documents"),
                ),
                (
                    "applies_to_document_type",
                    models.CharField(
                        blank=True,
                        help_text="Document type this policy applies to (empty = all types)",
                        max_length=100,
                    ),
                ),
                (
                    "auto_delete",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically delete documents after retention period",
                    ),
                ),
                (
                    "notification_days_before",
                    models.IntegerField(
                        default=30, help_text="Days before deletion to notify document owner"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applies_to_folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retention_policies",
                        to="folders.folder",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="retention_policies_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Retention Policy",
                "verbose_name_plural": "Retention Policies",
                "db_table": "retention_policies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LegalHoldDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legal_holds",
                        to="documents.document",
                    ),
                ),
                (
                    "legal_hold",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="held_documents",
                        to="retention.legalhold",
                    ),
                ),
                (
                    "placed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="legal_hold_documents_placed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Hold Document",
                "verbose_name_plural": "Legal Hold Documents",
                "db_table": "legal_hold_documents",
                "ordering": ["placed_at"],
                "unique_together": {("legal_hold", "document")},
            },
        ),
    ]
