# Generated by Django 5.2.8 on 2025-11-18 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("VIEW", "View"),
                            ("EDIT", "Edit"),
                            ("DELETE", "Delete"),
                            ("DOWNLOAD", "Download"),
                            ("SHARE", "Share"),
                            ("MOVE", "Move"),
                            ("COPY", "Copy"),
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("FAILED_LOGIN", "Failed Login"),
                            ("ACCOUNT_LOCKED", "Account Locked"),
                            ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                            ("PASSWORD_RESET", "Password Reset"),
                            ("MFA_ENABLED", "MFA Enabled"),
                            ("MFA_DISABLED", "MFA Disabled"),
                            ("PERMISSION_CHANGED", "Permission Changed"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Document"),
                            ("FOLDER", "Folder"),
                            ("USER", "User"),
                            ("TAG", "Tag"),
                            ("PERMISSION", "Permission"),
                            ("SHARE", "Share"),
                            ("RETENTION_POLICY", "Retention Policy"),
                            ("LEGAL_HOLD", "Legal Hold"),
                        ],
                        max_length=50,
                    ),
                ),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                ("resource_name", models.CharField(max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILURE", "Failure")], max_length=20
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context: before/after values, failed login count, etc.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "permissions": [("view_audit_log", "Can view audit logs")],
            },
        ),
    ]
