# Generated by Django 5.2.8 on 2025-11-19 00:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="after_value",
            field=models.JSONField(
                blank=True, help_text="State of the resource after the change", null=True
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="before_value",
            field=models.JSONField(
                blank=True, help_text="State of the resource before the change", null=True
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="changed_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                help_text="List of fields that were changed in this action",
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Create"),
                    ("VIEW", "View"),
                    ("EDIT", "Edit"),
                    ("DELETE", "Delete"),
                    ("DOWNLOAD", "Download"),
                    ("SHARE", "Share"),
                    ("MOVE", "Move"),
                    ("COPY", "Copy"),
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("ACCOUNT_LOCKED", "Account Locked"),
                    ("ACCOUNT_UNLOCKED", "Account Unlocked"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("MFA_ENABLED", "MFA Enabled"),
                    ("MFA_DISABLED", "MFA Disabled"),
                    ("PERMISSION_CHANGED", "Permission Changed"),
                    ("RESTORE", "Restore"),
                    ("ARCHIVE", "Archive"),
                    ("UNARCHIVE", "Unarchive"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional context: failed login count, session info, etc.",
            ),
        ),
    ]
