# Generated by Django 5.2.8 on 2025-11-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditlog_after_value_auditlog_before_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="resource_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
