# Generated by Django 5.2.8 on 2025-11-20 15:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0003_assign_data_to_default_org"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("issue_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("pdf_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "gateway_payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("gateway_charge_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLineItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "billing_invoice_line_items",
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("card", "Credit/Debit Card"),
                            ("bank_account", "Bank Account"),
                            ("paypal", "PayPal"),
                        ],
                        default="card",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "card_brand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("amex", "American Express"),
                            ("discover", "Discover"),
                            ("diners", "Diners Club"),
                            ("jcb", "JCB"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("card_last4", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "card_exp_month",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("card_exp_year", models.IntegerField(blank=True, null=True)),
                ("card_holder_name", models.CharField(blank=True, max_length=255, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                ("bank_account_type", models.CharField(blank=True, max_length=50, null=True)),
                ("bank_account_last4", models.CharField(blank=True, max_length=4, null=True)),
                ("bank_holder_name", models.CharField(blank=True, max_length=255, null=True)),
                ("paypal_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("gateway_payment_method_id", models.CharField(max_length=255, unique=True)),
                ("gateway_customer_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_payment_methods",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="billing.paymentmethod",
            ),
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("basic", "Basic"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "annual_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("max_users", models.IntegerField(default=-1)),
                ("max_storage_gb", models.IntegerField(default=10)),
                ("max_documents", models.IntegerField(default=1000)),
                ("max_folders", models.IntegerField(default=100)),
                ("max_api_calls_per_month", models.IntegerField(default=10000)),
                ("retention_policy_days", models.IntegerField(default=30)),
                ("audit_log_days", models.IntegerField(default=30)),
                ("versioning_per_document", models.IntegerField(default=5)),
                ("trial_days", models.IntegerField(blank=True, default=14, null=True)),
                ("features", models.JSONField(default=list)),
                ("highlighted", models.BooleanField(default=False)),
                ("popular", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "billing_plans",
                "ordering": ["monthly_price"],
                "indexes": [
                    models.Index(fields=["tier"], name="billing_pla_tier_e1c6b2_idx"),
                    models.Index(fields=["active"], name="billing_pla_active_97e3a8_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("max_redemptions", models.IntegerField(blank=True, null=True)),
                ("redemptions_count", models.IntegerField(default=0)),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("applicable_plans", models.ManyToManyField(blank=True, to="billing.plan")),
            ],
            options={
                "db_table": "billing_coupons",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("past_due", "Past Due"),
                            ("suspended", "Suspended"),
                            ("pending", "Pending"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("annual", "Annual")],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("cancellation_feedback", models.TextField(blank=True, null=True)),
                ("trial_start", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("trial_extended", models.BooleanField(default=False)),
                ("auto_renew", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "db_table": "billing_subscriptions",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="billing.subscription",
            ),
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("users", "Users"),
                            ("storage", "Storage (GB)"),
                            ("documents", "Documents"),
                            ("folders", "Folders"),
                            ("api_calls", "API Calls"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "billing_usage_records",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(fields=["organization"], name="billing_pay_organiz_bd6240_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(fields=["is_default"], name="billing_pay_is_defa_e38318_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["code"], name="billing_cou_code_3e81d6_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["active"], name="billing_cou_active_8df38d_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["organization"], name="billing_sub_organiz_124087_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="billing_sub_status_9d3b01_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["current_period_end"], name="billing_sub_current_8e7b0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["organization"], name="billing_inv_organiz_1e1261_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["subscription"], name="billing_inv_subscri_a97ea0_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="billing_inv_status_aefe38_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["invoice_number"], name="billing_inv_invoice_1d4853_idx"),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["organization", "metric_type", "recorded_at"],
                name="billing_usa_organiz_329866_idx",
            ),
        ),
    ]
