# Generated by Django 5.2.8 on 2025-11-18 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("folders", "0003_smartfolder"),
        ("users", "0002_department_storage_quota_gb"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("VIEWER", "Viewer"),
                            ("EDITOR", "Editor"),
                            ("MANAGER", "Manager"),
                            ("ADMIN", "Administrator"),
                        ],
                        help_text="Role name (VIEWER, EDITOR, MANAGER, ADMIN)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of role permissions and capabilities"
                    ),
                ),
                ("can_view", models.BooleanField(default=True)),
                ("can_download", models.BooleanField(default=True)),
                ("can_upload", models.BooleanField(default=False)),
                ("can_edit", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_share", models.BooleanField(default=False)),
                ("can_manage_permissions", models.BooleanField(default=False)),
                ("can_view_audit_log", models.BooleanField(default=False)),
                ("can_manage_retention", models.BooleanField(default=False)),
                ("can_manage_classification", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FolderPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("NO_ACCESS", "No Access"),
                            ("VIEW_ONLY", "View Only"),
                            ("VIEW_DOWNLOAD", "View & Download"),
                            ("CONTRIBUTE", "Contribute (Upload)"),
                            ("EDIT", "Edit"),
                            ("FULL_CONTROL", "Full Control"),
                        ],
                        default="VIEW_DOWNLOAD",
                        help_text="Level of access granted",
                        max_length=20,
                    ),
                ),
                (
                    "inherit_from_parent",
                    models.BooleanField(
                        default=True, help_text="Whether to inherit permissions from parent folder"
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department-wide permission",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_permissions",
                        to="users.department",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="folders.folder",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="folder_permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user (leave null for department-wide permission)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folder_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Folder Permission",
                "verbose_name_plural": "Folder Permissions",
                "db_table": "folder_permissions",
                "ordering": ["folder", "-granted_at"],
                "indexes": [
                    models.Index(fields=["folder", "user"], name="folder_perm_folder__d82465_idx"),
                    models.Index(
                        fields=["folder", "department"], name="folder_perm_folder__3bb4a6_idx"
                    ),
                    models.Index(fields=["user"], name="folder_perm_user_id_71e281_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("department__isnull", True), ("user__isnull", False)),
                            models.Q(("department__isnull", False), ("user__isnull", True)),
                            _connector="OR",
                        ),
                        name="either_user_or_department",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PermissionCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        help_text="Permission being checked (e.g., 'can_view', 'can_edit')",
                        max_length=50,
                    ),
                ),
                (
                    "has_permission",
                    models.BooleanField(
                        default=False, help_text="Whether user has this permission"
                    ),
                ),
                ("cached_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(help_text="When this cache entry expires")),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_cache",
                        to="folders.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_cache",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Cache Entry",
                "verbose_name_plural": "Permission Cache Entries",
                "db_table": "permission_cache",
                "ordering": ["-cached_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "folder", "permission_type"],
                        name="permission__user_id_4aae57_idx",
                    ),
                    models.Index(fields=["expires_at"], name="permission__expires_c49e09_idx"),
                ],
                "unique_together": {("user", "folder", "permission_type")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("GLOBAL", "Global"),
                            ("DEPARTMENT", "Department"),
                            ("FOLDER", "Folder"),
                        ],
                        default="GLOBAL",
                        help_text="Scope where this role applies",
                        max_length=20,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date for temporary roles",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department for DEPARTMENT scope",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="users.department",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="permissions.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role Assignment",
                "verbose_name_plural": "User Role Assignments",
                "db_table": "user_roles",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(fields=["user", "scope"], name="user_roles_user_id_bd904f_idx"),
                    models.Index(
                        fields=["user", "is_active"], name="user_roles_user_id_4ec42c_idx"
                    ),
                ],
                "unique_together": {("user", "role", "scope", "department")},
            },
        ),
    ]
