# Generated by Django 5.2.8 on 2025-12-02 06:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_increase_file_type_max_length"),
        ("permissions", "0001_initial"),
        ("users", "0013_add_user_settings_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("NO_ACCESS", "No Access"),
                            ("VIEW_ONLY", "View Only"),
                            ("VIEW_DOWNLOAD", "View & Download"),
                            ("EDIT", "Edit"),
                            ("FULL_CONTROL", "Full Control"),
                        ],
                        default="VIEW_DOWNLOAD",
                        help_text="Level of access granted",
                        max_length=20,
                    ),
                ),
                (
                    "override_folder_permissions",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this permission overrides folder-level permissions",
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date for temporary access",
                        null=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for granting/denying this permission"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="Department-wide permission",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_permissions",
                        to="users.department",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="documents.document",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific user (leave null for department-wide permission)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Permission",
                "verbose_name_plural": "Document Permissions",
                "db_table": "document_permissions",
                "ordering": ["document", "-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "user"], name="document_pe_documen_7d833c_idx"
                    ),
                    models.Index(
                        fields=["document", "department"], name="document_pe_documen_20af46_idx"
                    ),
                    models.Index(fields=["user"], name="document_pe_user_id_07267e_idx"),
                    models.Index(fields=["expires_at"], name="document_pe_expires_878911_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("department__isnull", True), ("user__isnull", False)),
                            models.Q(("department__isnull", False), ("user__isnull", True)),
                            _connector="OR",
                        ),
                        name="doc_either_user_or_department",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PermissionAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("GRANT", "Permission Granted"),
                            ("REVOKE", "Permission Revoked"),
                            ("MODIFY", "Permission Modified"),
                            ("EXPIRE", "Permission Expired"),
                            ("DENY", "Access Denied"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("FOLDER", "Folder"),
                            ("DOCUMENT", "Document"),
                            ("ROLE", "Role"),
                            ("DEPARTMENT", "Department"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_id", models.UUIDField()),
                ("old_permission_level", models.CharField(blank=True, max_length=20)),
                ("new_permission_level", models.CharField(blank=True, max_length=20)),
                ("reason", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_changes_received",
                        to="users.department",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permission_changes_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Audit Log",
                "verbose_name_plural": "Permission Audit Logs",
                "db_table": "permission_audit_log",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["actor", "timestamp"], name="permission__actor_i_778f73_idx"
                    ),
                    models.Index(
                        fields=["target_user", "timestamp"], name="permission__target__29a59b_idx"
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="permission__resourc_0036ea_idx",
                    ),
                    models.Index(fields=["-timestamp"], name="permission__timesta_e228bc_idx"),
                ],
            },
        ),
    ]
