# Generated by Django 5.2.8 on 2026-03-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0003_add_procedure_workflow_training_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissionauditlog",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("FOLDER", "Folder"),
                    ("DOCUMENT", "Document"),
                    ("ROLE", "Role"),
                    ("DEPARTMENT", "Department"),
                    ("PROCEDURE", "Procedure"),
                    ("WORKFLOW", "Workflow"),
                    ("TRAINING", "Training"),
                ],
                max_length=20,
            ),
        ),
    ]
