# Generated by Django 5.2.8 on 2026-03-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0004_extend_audit_log_resource_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="display_name",
            field=models.CharField(
                blank=True, help_text="Human-readable display name", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(
                default=False,
                help_text="True for built-in system roles that cannot be deleted or renamed",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                help_text="Role name — system roles: VIEWER, EDITOR, MANAGER, ADMIN; custom roles: any unique name",
                max_length=50,
                unique=True,
            ),
        ),
    ]
