# Generated by Django 5.2.8 on 2025-11-29 14:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0005_add_organization_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Friendly name for the API key", max_length=100),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 characters of the key for identification", max_length=8
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(help_text="SHA-256 hash of the full API key", max_length=64),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("read", "Read Only"),
                            ("write", "Read & Write"),
                            ("admin", "Full Admin Access"),
                        ],
                        default="read",
                        help_text="Access level for this API key",
                        max_length=20,
                    ),
                ),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed IP addresses (empty = all IPs allowed)",
                    ),
                ),
                (
                    "rate_limit",
                    models.PositiveIntegerField(
                        default=1000, help_text="Maximum requests per hour"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiration date", null=True
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_integration_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "integration_api_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("sso_saml", "SAML SSO"),
                            ("sso_oauth", "OAuth 2.0 SSO"),
                            ("sso_oidc", "OpenID Connect"),
                            ("ldap", "LDAP/Active Directory"),
                            ("aws_s3", "Amazon S3"),
                            ("azure_blob", "Azure Blob Storage"),
                            ("google_cloud", "Google Cloud Storage"),
                            ("sharepoint", "Microsoft SharePoint"),
                            ("onedrive", "Microsoft OneDrive"),
                            ("dropbox", "Dropbox Business"),
                            ("box", "Box"),
                            ("slack", "Slack"),
                            ("teams", "Microsoft Teams"),
                            ("email_smtp", "Custom SMTP"),
                            ("custom", "Custom Integration"),
                        ],
                        help_text="Type of integration",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for this integration", max_length=100),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the integration"),
                ),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Integration-specific configuration"),
                ),
                (
                    "credentials",
                    models.JSONField(
                        default=dict, help_text="Encrypted credentials for the integration"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Setup"),
                            ("testing", "Testing"),
                            ("active", "Active"),
                            ("error", "Error"),
                            ("disabled", "Disabled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "status_message",
                    models.TextField(
                        blank=True, help_text="Current status message or error details"
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configured_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "integration_services",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Friendly name for the webhook", max_length=100),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="HTTPS endpoint URL to receive events",
                        max_length=500,
                        validators=[django.core.validators.URLValidator(schemes=["https"])],
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Secret for signing webhook payloads", max_length=64
                    ),
                ),
                (
                    "subscribed_events",
                    models.JSONField(
                        default=list, help_text="List of event types to send to this webhook"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether the endpoint has been verified"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="Maximum retry attempts for failed deliveries"
                    ),
                ),
                (
                    "timeout_seconds",
                    models.PositiveSmallIntegerField(
                        default=30, help_text="Request timeout in seconds"
                    ),
                ),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                ("successful_deliveries", models.PositiveIntegerField(default=0)),
                ("failed_deliveries", models.PositiveIntegerField(default=0)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_reason", models.TextField(blank=True)),
                ("consecutive_failures", models.PositiveSmallIntegerField(default=0)),
                (
                    "auto_disabled",
                    models.BooleanField(
                        default=False, help_text="Automatically disabled due to repeated failures"
                    ),
                ),
                ("auto_disabled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "integration_webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("api_request", "API Request"),
                            ("webhook_delivery", "Webhook Delivery"),
                            ("integration_sync", "Integration Sync"),
                            ("config_change", "Configuration Change"),
                            ("auth_attempt", "Authentication Attempt"),
                            ("error", "Error"),
                        ],
                        max_length=30,
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                ("endpoint", models.CharField(blank=True, max_length=500)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("status_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="integrations.apikey",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="integrations.integration",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_logs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="integrations.webhook",
                    ),
                ),
            ],
            options={
                "db_table": "integration_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["organization", "is_active"], name="apikey_org_active_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["key_prefix"], name="apikey_prefix_idx"),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["organization", "status"], name="integration_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(fields=["integration_type"], name="integration_type_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="integration",
            unique_together={("organization", "integration_type", "name")},
        ),
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(fields=["organization", "is_active"], name="webhook_org_active_idx"),
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(fields=["organization", "created_at"], name="intlog_org_time_idx"),
        ),
        migrations.AddIndex(
            model_name="integrationlog",
            index=models.Index(fields=["action", "status"], name="intlog_action_status_idx"),
        ),
    ]
