# Generated by Django 5.2.8 on 2025-11-18 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("file_type", models.CharField(help_text="MIME type", max_length=50)),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 checksum for file integrity", max_length=64, unique=True
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("INVOICE", "Invoice"),
                            ("CONTRACT", "Contract"),
                            ("REPORT", "Report"),
                            ("KYC_RECORD", "KYC Record"),
                            ("FINANCIAL_STATEMENT", "Financial Statement"),
                            ("LOAN_APPLICATION", "Loan Application"),
                            ("IDENTITY_DOCUMENT", "Identity Document"),
                            ("CORRESPONDENCE", "Correspondence"),
                            ("POLICY", "Policy"),
                            ("PROCEDURE", "Procedure"),
                            ("AUDIT_REPORT", "Audit Report"),
                            ("COMPLIANCE_DOC", "Compliance Document"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=100,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Customer ID, Contract Number, Invoice Number, etc.",
                        max_length=255,
                    ),
                ),
                ("document_date", models.DateField()),
                (
                    "creator_source",
                    models.CharField(
                        help_text="Original creator or source of the document", max_length=255
                    ),
                ),
                (
                    "confidentiality_level",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                (
                    "retention_period_years",
                    models.IntegerField(
                        default=7, help_text="Number of years to retain this document"
                    ),
                ),
                ("version_number", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="Text extracted from document for search indexing"
                    ),
                ),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True, help_text="OCR confidence score (0.0 to 1.0)", null=True
                    ),
                ),
                (
                    "is_indexed",
                    models.BooleanField(
                        default=False, help_text="Whether document has been indexed for search"
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "db_table": "documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Document Tag",
                "verbose_name_plural": "Document Tags",
                "db_table": "document_tags",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#808080", help_text="Hex color code (e.g., #FF5733)", max_length=7
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "db_table": "tags",
                "ordering": ["name"],
            },
        ),
    ]
