# Generated by Django 5.2.8 on 2025-11-18 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("folders", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="folders.folder",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="parent_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="documenttag",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="documenttag",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_tags",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tags_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="documenttag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tagged_documents",
                to="documents.tag",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["folder"], name="documents_folder__5c7d69_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["owner"], name="documents_owner_i_3fe723_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["department"], name="documents_departm_ec72b9_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["document_type"], name="documents_documen_fc21d0_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["document_date"], name="documents_documen_718437_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["checksum"], name="documents_checksu_208ee8_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["created_at"], name="documents_created_3c6eaa_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["is_deleted"], name="documents_is_dele_636b14_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documenttag",
            unique_together={("document", "tag")},
        ),
    ]
