# Generated by Django 5.2.8 on 2025-11-18 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
        ("folders", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChunkedUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("upload_id", models.CharField(max_length=100, unique=True)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(help_text="Total file size in bytes")),
                (
                    "chunk_size",
                    models.IntegerField(
                        default=5242880, help_text="Chunk size in bytes (default 5MB)"
                    ),
                ),
                ("total_chunks", models.IntegerField()),
                (
                    "uploaded_chunks",
                    models.JSONField(default=list, help_text="List of uploaded chunk numbers"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADING", "Uploading"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="UPLOADING",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(default=dict, help_text="Metadata for final document"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField(help_text="Upload session expiration time")),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="folders.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunked_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chunked Upload",
                "verbose_name_plural": "Chunked Uploads",
                "db_table": "chunked_uploads",
                "ordering": ["-created_at"],
            },
        ),
    ]
