# Generated by Django 5.2.8 on 2025-11-18 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_chunkedupload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(help_text="Sequential version number (1, 2, 3, ...)"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="File storage path for this version",
                        upload_to="versions/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original filename for this version", max_length=255
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("file_type", models.CharField(help_text="MIME type", max_length=50)),
                (
                    "checksum",
                    models.CharField(
                        help_text="SHA-256 checksum for version integrity verification",
                        max_length=64,
                    ),
                ),
                (
                    "change_description",
                    models.TextField(
                        blank=True, help_text="Description of changes in this version"
                    ),
                ),
                (
                    "is_major_version",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a major version (significant changes)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "storage_key",
                    models.CharField(
                        blank=True, help_text="MinIO storage key for this version", max_length=500
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_versions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="The document this version belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_versions",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Version",
                "verbose_name_plural": "Document Versions",
                "db_table": "document_versions",
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["document", "-version_number"],
                        name="document_ve_documen_c3917c_idx",
                    ),
                    models.Index(fields=["created_at"], name="document_ve_created_c8d81d_idx"),
                    models.Index(fields=["checksum"], name="document_ve_checksu_34a74a_idx"),
                ],
                "unique_together": {("document", "version_number")},
            },
        ),
    ]
