# Generated by Django 5.2.8 on 2025-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_documentversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="pdf_version_path",
            field=models.CharField(
                blank=True,
                help_text="Path to PDF version of document (for Office files)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="thumbnail_path",
            field=models.CharField(
                blank=True,
                help_text="Path to thumbnail image in storage (200x200 JPEG)",
                max_length=500,
                null=True,
            ),
        ),
    ]
