# Generated by Django 5.2.8 on 2025-11-19 00:53

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_document_pdf_version_path_document_thumbnail_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="account_number",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted account number (sensitive financial data)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="customer_id",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted customer identifier (PII)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="notes",
            field=apps.core.fields.EncryptedTextField(
                blank=True,
                help_text="Encrypted internal notes (may contain sensitive information)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="tax_id",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Encrypted tax ID/SSN (PII - Personally Identifiable Information)",
                max_length=255,
                null=True,
            ),
        ),
    ]
