# Generated by Django 5.2.8 on 2025-11-19 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_document_account_number_document_customer_id_and_more"),
        ("organizations", "0002_create_default_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization this document belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documents",
                to="organizations.organization",
            ),
        ),
    ]
