# Generated by Django 5.2.8 on 2025-11-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_add_organization_to_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="minio_bucket",
            field=models.CharField(
                blank=True, help_text="MinIO bucket name where file is stored", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="minio_etag",
            field=models.CharField(
                blank=True, help_text="S3 ETag for file integrity verification", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="minio_object_key",
            field=models.CharField(
                blank=True, help_text="MinIO object key (path) for the file", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="storage_region",
            field=models.CharField(default="us-east-1", help_text="Storage region", max_length=50),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="minio_bucket",
            field=models.CharField(
                blank=True,
                help_text="MinIO bucket name where version file is stored",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="minio_etag",
            field=models.CharField(
                blank=True,
                help_text="S3 ETag for version file integrity verification",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="documentversion",
            name="minio_object_key",
            field=models.CharField(
                blank=True, help_text="MinIO object key (path) for the version file", max_length=500
            ),
        ),
    ]
