# Generated by Django 5.2.8 on 2025-11-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_add_minio_storage_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("INVOICE", "Invoice"),
                    ("CONTRACT", "Contract"),
                    ("REPORT", "Report"),
                    ("KYC_RECORD", "KYC Record"),
                    ("STATEMENT", "Statement"),
                    ("FINANCIAL_STATEMENT", "Financial Statement"),
                    ("CORRESPONDENCE", "Correspondence"),
                    ("POLICY_DOCUMENT", "Policy"),
                    ("POLICY", "Policy"),
                    ("PROCEDURE_DOCUMENT", "Procedure"),
                    ("PROCEDURE", "Procedure"),
                    ("MEMO", "Memo"),
                    ("PRESENTATION", "Presentation"),
                    ("SPREADSHEET", "Spreadsheet"),
                    ("FORM", "Form"),
                    ("CERTIFICATE", "Certificate"),
                    ("AGREEMENT", "Agreement"),
                    ("AUDIT_REPORT", "Audit Report"),
                    ("BANK_STATEMENT", "Bank Statement"),
                    ("TAX_DOCUMENT", "Tax Document"),
                    ("LEGAL_DOCUMENT", "Legal Document"),
                    ("PASSPORT", "Passport"),
                    ("ID_CARD", "ID Card"),
                    ("LOAN_APPLICATION", "Loan Application"),
                    ("IDENTITY_DOCUMENT", "Identity Document"),
                    ("COMPLIANCE_DOC", "Compliance Document"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=100,
            ),
        ),
    ]
