# Generated by Django 5.2.8 on 2025-11-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_fix_nullable_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Legacy file field - files are stored in MinIO, not here",
                null=True,
                upload_to="documents/%Y/%m/%d/",
            ),
        ),
    ]
