# Generated by Django 5.2.8 on 2025-11-25 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_make_file_field_optional"),
        ("folders", "0004_add_organization_to_folder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentShortcut",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this shortcut",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shortcuts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        help_text="The folder where this shortcut appears",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_shortcuts",
                        to="folders.folder",
                    ),
                ),
                (
                    "original_document",
                    models.ForeignKey(
                        help_text="The original document this shortcut points to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shortcuts",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Shortcut",
                "verbose_name_plural": "Document Shortcuts",
                "db_table": "document_shortcuts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["folder"], name="document_sh_folder__f64b32_idx"),
                    models.Index(
                        fields=["original_document"], name="document_sh_origina_9bd4e3_idx"
                    ),
                    models.Index(fields=["created_at"], name="document_sh_created_360162_idx"),
                ],
                "unique_together": {("original_document", "folder")},
            },
        ),
    ]
