# Generated by Django 5.2.8 on 2025-11-26 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_create_document_shortcut"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("DOCUMENT", "Document"), ("FOLDER", "Folder")], max_length=20
                    ),
                ),
                ("resource_id", models.UUIDField(help_text="UUID of the document or folder")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("VIEWED", "Viewed"),
                            ("EDITED", "Edited"),
                            ("UPLOADED", "Uploaded"),
                            ("DOWNLOADED", "Downloaded"),
                            ("SHARED", "Shared"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resource_name",
                    models.CharField(help_text="Name of the document or folder", max_length=500),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, help_text="MIME type (for documents only)", max_length=50
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        default=0, help_text="File size in bytes (for documents only)"
                    ),
                ),
                (
                    "folder_id",
                    models.UUIDField(blank=True, help_text="Parent folder UUID", null=True),
                ),
                (
                    "folder_name",
                    models.CharField(blank=True, help_text="Parent folder name", max_length=255),
                ),
                (
                    "folder_path",
                    models.CharField(
                        blank=True, help_text="Full path to the resource", max_length=1000
                    ),
                ),
                (
                    "confidentiality_level",
                    models.CharField(
                        blank=True,
                        help_text="Confidentiality level (PUBLIC, INTERNAL, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Whether this item is pinned by the user"
                    ),
                ),
                (
                    "pinned_at",
                    models.DateTimeField(
                        blank=True, help_text="When the item was pinned", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recent Activity",
                "verbose_name_plural": "Recent Activities",
                "db_table": "recent_activities",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"], name="recent_acti_user_id_3e59a2_idx"
                    ),
                    models.Index(
                        fields=["user", "resource_type", "-timestamp"],
                        name="recent_acti_user_id_abac90_idx",
                    ),
                    models.Index(
                        fields=["user", "activity_type", "-timestamp"],
                        name="recent_acti_user_id_4c23f9_idx",
                    ),
                    models.Index(
                        fields=["user", "is_pinned", "-timestamp"],
                        name="recent_acti_user_id_30ee55_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="recent_acti_resourc_b808dd_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "resource_type", "resource_id", "activity_type"),
                        name="unique_user_resource_activity",
                    )
                ],
            },
        ),
    ]
