# Generated by Django 5.2.8 on 2025-11-26 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_create_recent_activity"),
        ("folders", "0006_add_soft_delete_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PinnedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Document"),
                            ("FOLDER", "Folder"),
                            ("SHARED_DOCUMENT", "Shared Document"),
                            ("SHARED_FOLDER", "Shared Folder"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shared_item_id",
                    models.UUIDField(
                        blank=True, help_text="ID of SharedItemAccess for shared items", null=True
                    ),
                ),
                (
                    "shared_item_name",
                    models.CharField(
                        blank=True, help_text="Cached name for shared items", max_length=500
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Order of item in Quick Access (lower = first)",
                    ),
                ),
                (
                    "custom_label",
                    models.CharField(
                        blank=True, help_text="Custom display label (optional)", max_length=255
                    ),
                ),
                ("pinned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="documents.document",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pins",
                        to="folders.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pinned_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pinned Item",
                "verbose_name_plural": "Pinned Items",
                "db_table": "pinned_items",
                "ordering": ["display_order", "-pinned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "display_order"], name="pinned_item_user_id_a05aa7_idx"
                    ),
                    models.Index(
                        fields=["user", "item_type"], name="pinned_item_user_id_789eba_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("document__isnull", False)),
                        fields=("user", "document"),
                        name="unique_user_document_pin",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("folder__isnull", False)),
                        fields=("user", "folder"),
                        name="unique_user_folder_pin",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("shared_item_id__isnull", False)),
                        fields=("user", "shared_item_id"),
                        name="unique_user_shared_item_pin",
                    ),
                ],
            },
        ),
    ]
