# Generated by Django 5.2.8 on 2025-11-26 15:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_pinned_items"),
        ("folders", "0006_add_soft_delete_fields"),
        ("organizations", "0004_add_company_registration_fields"),
        ("users", "0012_add_share_protection_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentStateTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        help_text="Previous state",
                        max_length=20,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("PUBLISHED", "Published"),
                            ("ARCHIVED", "Archived"),
                        ],
                        help_text="New state",
                        max_length=20,
                    ),
                ),
                (
                    "transitioned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the state change occurred"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Optional notes for this transition"),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, help_text="Reason for rejection (if applicable)"),
                ),
            ],
            options={
                "verbose_name": "Document State Transition",
                "verbose_name_plural": "Document State Transitions",
                "db_table": "document_state_transitions",
                "ordering": ["-transitioned_at"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="approved_at",
            field=models.DateTimeField(
                blank=True, help_text="When document was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who approved the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, help_text="When document was archived", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who archived the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_archived",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="published_at",
            field=models.DateTimeField(
                blank=True, help_text="When document was published", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="published_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who published the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_published",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="rejection_reason",
            field=models.TextField(blank=True, help_text="Reason for rejection (if rejected)"),
        ),
        migrations.AddField(
            model_name="document",
            name="review_notes",
            field=models.TextField(blank=True, help_text="Notes from reviewer (optional)"),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When document was reviewed (approved/rejected)", null=True
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reviewed the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="state",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("IN_REVIEW", "In Review"),
                    ("APPROVED", "Approved"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                db_index=True,
                default="DRAFT",
                help_text="Current lifecycle state of the document",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted the document for review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="submitted_for_review_at",
            field=models.DateTimeField(
                blank=True, help_text="When document was submitted for review", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["state"], name="documents_state_fe74b7_idx"),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(fields=["state", "owner"], name="documents_state_99392e_idx"),
        ),
        migrations.AddField(
            model_name="documentstatetransition",
            name="document",
            field=models.ForeignKey(
                help_text="Document that changed state",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="state_transitions",
                to="documents.document",
            ),
        ),
        migrations.AddField(
            model_name="documentstatetransition",
            name="transitioned_by",
            field=models.ForeignKey(
                help_text="User who made the state change",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="document_state_transitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="documentstatetransition",
            index=models.Index(
                fields=["document", "-transitioned_at"], name="document_st_documen_4218e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentstatetransition",
            index=models.Index(
                fields=["transitioned_by", "-transitioned_at"],
                name="document_st_transit_205d4d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentstatetransition",
            index=models.Index(
                fields=["from_state", "to_state"], name="document_st_from_st_67dbe5_idx"
            ),
        ),
    ]
