# Generated by Django 5.2.8 on 2025-12-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0015_document_states"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_type",
            field=models.CharField(help_text="MIME type", max_length=100),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="file_type",
            field=models.CharField(help_text="MIME type", max_length=100),
        ),
        migrations.AlterField(
            model_name="recentactivity",
            name="file_type",
            field=models.CharField(
                blank=True, help_text="MIME type (for documents only)", max_length=100
            ),
        ),
    ]
