# Generated by Django 5.2.8 on 2025-12-02 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_increase_file_type_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted the document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
