# Generated by Django 5.2.8 on 2025-12-03 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("result_count", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recent_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Recent Search",
                "verbose_name_plural": "Recent Searches",
                "db_table": "search_recent_searches",
                "ordering": ["-executed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-executed_at"], name="search_rece_user_id_9c76bb_idx"
                    )
                ],
            },
        ),
    ]
