# Generated by Django 5.2.8 on 2025-11-18 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("path", models.TextField(help_text="Full folder path for efficient tree queries")),
                ("depth", models.IntegerField(default=0)),
                (
                    "confidentiality_level",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("INTERNAL", "Internal"),
                            ("CONFIDENTIAL", "Confidential"),
                            ("HIGHLY_CONFIDENTIAL", "Highly Confidential"),
                        ],
                        default="INTERNAL",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Folder",
                "verbose_name_plural": "Folders",
                "db_table": "folders",
                "ordering": ["path", "name"],
            },
        ),
        migrations.CreateModel(
            name="FolderTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "structure",
                    models.JSONField(help_text="JSON structure defining the folder hierarchy"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Folder Template",
                "verbose_name_plural": "Folder Templates",
                "db_table": "folder_templates",
                "ordering": ["name"],
            },
        ),
    ]
