# Generated by Django 5.2.8 on 2025-11-18 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("folders", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="folders_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="folders",
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_folders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="folders.folder",
            ),
        ),
        migrations.AddField(
            model_name="foldertemplate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="folder_templates_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="foldertemplate",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_templates",
                to="users.department",
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["parent"], name="folders_parent__95398b_idx"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["path"], name="folders_path_41fee0_idx"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["owner"], name="folders_owner_i_b7b606_idx"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["department"], name="folders_departm_b2813e_idx"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["created_at"], name="folders_created_bcede5_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("parent", "name")},
        ),
    ]
