# Generated by Django 5.2.8 on 2025-11-18 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0002_initial"),
        ("users", "0002_department_storage_quota_gb"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Display name for the smart folder", max_length=255),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what documents this smart folder contains",
                    ),
                ),
                (
                    "criteria",
                    models.JSONField(help_text="JSON object defining search/filter criteria"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("star", "Star"),
                            ("bookmark", "Bookmark"),
                            ("filter", "Filter"),
                            ("search", "Search"),
                            ("tag", "Tag"),
                            ("folder_special", "Special Folder"),
                        ],
                        default="folder_special",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FF5733", "Red"),
                            ("#33FF57", "Green"),
                            ("#3357FF", "Blue"),
                            ("#FF33F5", "Purple"),
                            ("#F5FF33", "Yellow"),
                            ("#33FFF5", "Cyan"),
                            ("#FF8C33", "Orange"),
                        ],
                        default="#3357FF",
                        max_length=7,
                    ),
                ),
                (
                    "is_personal",
                    models.BooleanField(
                        default=True,
                        help_text="If True, only visible to owner; if False, shared with department",
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False,
                        help_text="If True, visible to all users (admin-created smart folders)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this smart folder is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_count",
                    models.IntegerField(
                        default=0,
                        help_text="Cached count of matching documents (updated periodically)",
                    ),
                ),
                (
                    "last_count_update",
                    models.DateTimeField(
                        blank=True, help_text="When document_count was last updated", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="smart_folders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, smart folder is visible to entire department",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_folders",
                        to="users.department",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who created this smart folder",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="smart_folders_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Folder",
                "verbose_name_plural": "Smart Folders",
                "db_table": "smart_folders",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["owner"], name="smart_folde_owner_i_ffce5a_idx"),
                    models.Index(fields=["department"], name="smart_folde_departm_6a86ad_idx"),
                    models.Index(fields=["is_personal"], name="smart_folde_is_pers_1a8f90_idx"),
                    models.Index(fields=["is_global"], name="smart_folde_is_glob_8e0cce_idx"),
                    models.Index(fields=["is_active"], name="smart_folde_is_acti_810637_idx"),
                    models.Index(fields=["created_at"], name="smart_folde_created_37389d_idx"),
                ],
            },
        ),
    ]
