# Generated by Django 5.2.8 on 2025-11-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0005_add_is_locked_field"),
        ("organizations", "0004_add_company_registration_fields"),
        ("users", "0010_add_favorites_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, help_text="When the folder was moved to trash", null=True
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this folder",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folders_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="folder",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="If True, folder is in trash"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["is_deleted"], name="folders_is_dele_08a3ee_idx"),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(fields=["deleted_at"], name="folders_deleted_66c01d_idx"),
        ),
    ]
