# Generated by Django 5.2.8 on 2025-11-26 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0006_add_soft_delete_fields"),
        ("users", "0012_add_share_protection_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smartfolder",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name": "Smart Folder",
                "verbose_name_plural": "Smart Folders",
            },
        ),
        migrations.AddField(
            model_name="smartfolder",
            name="display_order",
            field=models.IntegerField(
                db_index=True, default=0, help_text="Order in which to display in sidebar"
            ),
        ),
        migrations.AddField(
            model_name="smartfolder",
            name="include_owned",
            field=models.BooleanField(
                default=True, help_text="Include documents owned by the user"
            ),
        ),
        migrations.AddField(
            model_name="smartfolder",
            name="include_shared",
            field=models.BooleanField(
                default=False, help_text="Include documents shared with the user"
            ),
        ),
        migrations.AddField(
            model_name="smartfolder",
            name="is_visible",
            field=models.BooleanField(default=True, help_text="Whether to show in sidebar"),
        ),
        migrations.AddIndex(
            model_name="smartfolder",
            index=models.Index(
                fields=["owner", "display_order"], name="smart_folde_owner_i_4b7c74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smartfolder",
            index=models.Index(
                fields=["owner", "is_visible"], name="smart_folde_owner_i_9ec3c8_idx"
            ),
        ),
    ]
