# Generated by Django 5.2.8 on 2025-12-03 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("folders", "0009_department_as_root_constraints"),
        ("users", "0016_department_settings_and_cross_access"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="folder",
            new_name="folders_departm_ef155b_idx",
            old_name="folder_dept_parent_idx",
        ),
        migrations.RenameIndex(
            model_name="folder",
            new_name="folders_departm_4b1154_idx",
            old_name="folder_dept_deleted_idx",
        ),
        migrations.AlterField(
            model_name="folder",
            name="department",
            field=models.ForeignKey(
                help_text="Department this folder belongs to (required - acts as root container)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="folders",
                to="users.department",
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="path",
            field=models.TextField(
                db_index=True, help_text="Full folder path including department code prefix"
            ),
        ),
    ]
