# Generated by Django 5.2.8 on 2025-11-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of consecutive failed login attempts"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="Account locked due to too many failed login attempts",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="locked_at",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp when account was locked", null=True
            ),
        ),
    ]
