"""
Celery tasks for the Procedures app.

Phase G: Evidence export tasks
Phase H: Assignment reminders, overdue detection, expiry checks, recertification
"""

import csv
import io
import logging
from datetime import date, timedelta

from celery import shared_task
from django.utils import timezone

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Phase G: Evidence Export Tasks
# ---------------------------------------------------------------------------

@shared_task
def export_evidence_pdf(filter_params, requested_by_id):
    """
    On-demand: Generate PDF evidence report asynchronously.

    Generates a PDF containing:
    - Header: Organization name, report date, procedure title + version
    - Assignee details: name, department, role
    - Assignment summary: dates, status, score
    - Attempt timeline: each attempt with step-by-step evidence
    - Quiz results: per-question breakdown
    - Footer: "Generated by DFC — Digital Filing Cabinet"

    The generated file is stored in MinIO and the user is notified.
    """
    from .models import ProcedureAssignment
    from apps.users.models import CustomUser

    try:
        requested_by = CustomUser.objects.get(id=requested_by_id)
        org = requested_by.organization

        qs = ProcedureAssignment.objects.filter(
            organization=org,
        ).select_related(
            'procedure_version__procedure', 'assignee', 'assigned_by',
        ).prefetch_related(
            'attempts__step_completions__version_step',
            'attempts__quiz_attempts__responses__version_question',
        )

        # Apply filters
        if filter_params.get('user'):
            qs = qs.filter(assignee_id=filter_params['user'])
        if filter_params.get('procedure'):
            qs = qs.filter(procedure_version__procedure_id=filter_params['procedure'])
        if filter_params.get('date_from'):
            qs = qs.filter(assigned_at__date__gte=filter_params['date_from'])
        if filter_params.get('date_to'):
            qs = qs.filter(assigned_at__date__lte=filter_params['date_to'])
        if filter_params.get('status'):
            qs = qs.filter(status=filter_params['status'])

        # Try to use reportlab for PDF generation
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.units import inch
            from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            from reportlab.lib.styles import getSampleStyleSheet
            from reportlab.lib import colors

            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=A4)
            styles = getSampleStyleSheet()
            elements = []

            # Title
            elements.append(Paragraph(
                f"Training Evidence Report — {org.name}",
                styles['Title']
            ))
            elements.append(Paragraph(
                f"Generated: {timezone.now().strftime('%Y-%m-%d %H:%M UTC')}",
                styles['Normal']
            ))
            elements.append(Spacer(1, 0.3 * inch))

            for assignment in qs[:100]:  # Limit to prevent huge reports
                version = assignment.procedure_version

                # Assignment header
                elements.append(Paragraph(
                    f"{version.title} (v{version.version_number})",
                    styles['Heading2']
                ))

                # Summary table
                summary_data = [
                    ['Assignee', assignment.assignee.get_full_name()],
                    ['Email', assignment.assignee.email],
                    ['Assigned By', assignment.assigned_by.get_full_name()],
                    ['Assigned At', assignment.assigned_at.strftime('%Y-%m-%d')],
                    ['Due Date', str(assignment.due_date)],
                    ['Status', assignment.status.upper()],
                    ['Completion Score', f"{assignment.completion_score}%" if assignment.completion_score else 'N/A'],
                ]
                summary_table = Table(summary_data, colWidths=[2 * inch, 4 * inch])
                summary_table.setStyle(TableStyle([
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('BACKGROUND', (0, 0), (0, -1), colors.Color(0.9, 0.9, 0.9)),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('PADDING', (0, 0), (-1, -1), 4),
                ]))
                elements.append(summary_table)
                elements.append(Spacer(1, 0.2 * inch))

                # Attempts
                for attempt in assignment.attempts.all().order_by('attempt_number'):
                    elements.append(Paragraph(
                        f"Attempt #{attempt.attempt_number} — {attempt.status}",
                        styles['Heading3']
                    ))

                    # Step completions table
                    step_data = [['Step', 'Status', 'Time (s)', 'Completed At']]
                    for sc in attempt.step_completions.all().order_by('version_step__order'):
                        step_data.append([
                            f"{sc.version_step.order}. {sc.version_step.title[:40]}",
                            sc.status,
                            str(sc.time_spent_seconds),
                            sc.completed_at.strftime('%Y-%m-%d %H:%M') if sc.completed_at else '',
                        ])

                    if len(step_data) > 1:
                        step_table = Table(step_data, colWidths=[2.5 * inch, 1.2 * inch, 0.8 * inch, 1.5 * inch])
                        step_table.setStyle(TableStyle([
                            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                            ('BACKGROUND', (0, 0), (-1, 0), colors.Color(0.8, 0.8, 0.8)),
                            ('FONTSIZE', (0, 0), (-1, -1), 8),
                            ('PADDING', (0, 0), (-1, -1), 3),
                        ]))
                        elements.append(step_table)

                    # Quiz results
                    for qa in attempt.quiz_attempts.all():
                        elements.append(Paragraph(
                            f"Quiz: {qa.version_quiz.title} — "
                            f"{'PASSED' if qa.passed else 'FAILED'} "
                            f"({qa.score_percent}%)",
                            styles['Normal']
                        ))

                    elements.append(Spacer(1, 0.2 * inch))

                elements.append(Spacer(1, 0.3 * inch))

            # Footer
            elements.append(Paragraph(
                "Generated by DFC — Digital Filing Cabinet",
                styles['Normal']
            ))

            doc.build(elements)
            pdf_bytes = buffer.getvalue()
            buffer.close()

        except ImportError:
            # Fallback: generate a simple text-based report if reportlab not installed
            logger.warning("reportlab not installed. Generating text-based evidence report.")
            lines = [f"Training Evidence Report — {org.name}"]
            lines.append(f"Generated: {timezone.now().strftime('%Y-%m-%d %H:%M UTC')}")
            lines.append("=" * 60)

            for assignment in qs[:100]:
                version = assignment.procedure_version
                lines.append(f"\n{version.title} (v{version.version_number})")
                lines.append(f"Assignee: {assignment.assignee.get_full_name()}")
                lines.append(f"Status: {assignment.status}")
                lines.append(f"Score: {assignment.completion_score or 'N/A'}")

                for attempt in assignment.attempts.all().order_by('attempt_number'):
                    lines.append(f"  Attempt #{attempt.attempt_number}: {attempt.status}")
                    for sc in attempt.step_completions.all().order_by('version_step__order'):
                        lines.append(f"    Step {sc.version_step.order}: {sc.version_step.title} — {sc.status}")

            lines.append("\nGenerated by DFC — Digital Filing Cabinet")
            pdf_bytes = "\n".join(lines).encode('utf-8')

        # Store the file (in MinIO via Django storage)
        from django.core.files.base import ContentFile
        from django.core.files.storage import default_storage

        filename = f"exports/evidence/evidence_report_{timezone.now().strftime('%Y%m%d_%H%M%S')}_{requested_by_id[:8]}.pdf"
        saved_path = default_storage.save(filename, ContentFile(pdf_bytes))

        logger.info(f"Evidence PDF exported to {saved_path} for user {requested_by_id}")

        # TODO: Send notification to requested_by user with download link
        return {'status': 'success', 'path': saved_path}

    except Exception as e:
        logger.error(f"Evidence PDF export failed: {e}")
        return {'status': 'error', 'message': str(e)}


@shared_task
def export_evidence_csv(filter_params, requested_by_id):
    """
    On-demand: Generate CSV evidence export asynchronously.
    Used for large exports that would timeout synchronously.
    """
    from .models import ProcedureAssignment
    from apps.users.models import CustomUser

    try:
        requested_by = CustomUser.objects.get(id=requested_by_id)
        org = requested_by.organization

        qs = ProcedureAssignment.objects.filter(
            organization=org,
        ).select_related(
            'procedure_version__procedure', 'assignee', 'assigned_by',
        ).prefetch_related('attempts')

        # Apply filters
        if filter_params.get('user'):
            qs = qs.filter(assignee_id=filter_params['user'])
        if filter_params.get('procedure'):
            qs = qs.filter(procedure_version__procedure_id=filter_params['procedure'])
        if filter_params.get('date_from'):
            qs = qs.filter(assigned_at__date__gte=filter_params['date_from'])
        if filter_params.get('date_to'):
            qs = qs.filter(assigned_at__date__lte=filter_params['date_to'])
        if filter_params.get('status'):
            qs = qs.filter(status=filter_params['status'])

        output = io.StringIO()
        writer = csv.writer(output)
        writer.writerow([
            'assignment_id', 'procedure_title', 'version_number',
            'assignee_name', 'assignee_email', 'department',
            'assigned_by', 'assigned_at', 'due_date', 'source',
            'status', 'completed_at', 'completion_score',
            'total_attempts', 'total_time_seconds',
        ])

        for assignment in qs:
            total_time = sum(a.total_time_seconds for a in assignment.attempts.all())
            dept = getattr(assignment.assignee, 'department', None)
            writer.writerow([
                str(assignment.id),
                assignment.procedure_version.title,
                assignment.procedure_version.version_number,
                assignment.assignee.get_full_name(),
                assignment.assignee.email,
                dept.name if dept else '',
                assignment.assigned_by.get_full_name(),
                assignment.assigned_at.isoformat(),
                str(assignment.due_date),
                assignment.assignment_source,
                assignment.status,
                assignment.completed_at.isoformat() if assignment.completed_at else '',
                str(assignment.completion_score or ''),
                assignment.attempts.count(),
                total_time,
            ])

        # Store the file
        from django.core.files.base import ContentFile
        from django.core.files.storage import default_storage

        csv_bytes = output.getvalue().encode('utf-8')
        filename = f"exports/evidence/evidence_export_{timezone.now().strftime('%Y%m%d_%H%M%S')}_{requested_by_id[:8]}.csv"
        saved_path = default_storage.save(filename, ContentFile(csv_bytes))

        logger.info(f"Evidence CSV exported to {saved_path} for user {requested_by_id}")

        # TODO: Send notification to requested_by user with download link
        return {'status': 'success', 'path': saved_path}

    except Exception as e:
        logger.error(f"Evidence CSV export failed: {e}")
        return {'status': 'error', 'message': str(e)}


# ---------------------------------------------------------------------------
# Phase H: Scheduled Tasks (stubs — to be fully implemented in Phase H)
# ---------------------------------------------------------------------------

@shared_task
def send_assignment_reminders():
    """Daily: Send reminder notifications for upcoming due dates."""
    from .models import ProcedureAssignment

    today = date.today()
    cadences = [7, 3, 1]  # Days before due

    for days_before in cadences:
        target_date = today + timedelta(days=days_before)
        assignments = ProcedureAssignment.objects.filter(
            due_date=target_date,
            status__in=['assigned', 'in_progress'],
        ).select_related('assignee', 'procedure_version')

        for assignment in assignments:
            # TODO: Send notification via notification system
            assignment.last_reminder_sent = timezone.now()
            assignment.reminder_count += 1
            assignment.save(update_fields=['last_reminder_sent', 'reminder_count'])

            logger.info(
                f"Reminder sent to {assignment.assignee} for "
                f"{assignment.procedure_version.title} (due in {days_before} days)"
            )


@shared_task
def check_overdue_assignments():
    """Daily: Mark overdue assignments and notify admins."""
    from .models import ProcedureAssignment

    updated = ProcedureAssignment.objects.filter(
        status__in=['assigned', 'in_progress'],
        due_date__lt=date.today(),
    ).update(status='overdue')

    logger.info(f"Marked {updated} assignments as overdue")
    return {'overdue_count': updated}


@shared_task
def check_expiring_versions():
    """Daily: Check for versions expiring within 30 days."""
    from .models import ProcedureVersion

    threshold = date.today() + timedelta(days=30)
    expiring = ProcedureVersion.objects.filter(
        is_active=True,
        expires_on__lte=threshold,
        expires_on__gte=date.today(),
    ).select_related('procedure')

    for version in expiring:
        # TODO: Send notification to admin
        logger.info(
            f"Version expiring soon: {version.title} v{version.version_number} "
            f"(expires {version.expires_on})"
        )

    return {'expiring_count': expiring.count()}


@shared_task
def auto_generate_recertifications():
    """Daily: Create re-certification assignments for expired versions."""
    from .models import ProcedureVersion, ProcedureAssignment

    expired = ProcedureVersion.objects.filter(
        is_active=True,
        expires_on__lt=date.today(),
    ).select_related('procedure')

    recert_count = 0
    for version in expired:
        # Check if a newer published version exists
        newer = ProcedureVersion.objects.filter(
            procedure=version.procedure,
            is_active=True,
            version_number__gt=version.version_number,
        ).first()

        if newer:
            # Find all users who completed the old version
            completed_users = ProcedureAssignment.objects.filter(
                procedure_version=version,
                status='completed',
            ).values_list('assignee_id', flat=True)

            # Skip already-assigned users
            already_assigned = ProcedureAssignment.objects.filter(
                procedure_version=newer,
                assignee_id__in=completed_users,
                status__in=['assigned', 'in_progress', 'completed'],
            ).values_list('assignee_id', flat=True)

            to_assign = set(completed_users) - set(already_assigned)

            for user_id in to_assign:
                ProcedureAssignment.objects.create(
                    organization=version.procedure.organization,
                    procedure_version=newer,
                    assignee_id=user_id,
                    assigned_by_id=version.published_by_id,
                    assignment_source='recertification',
                    due_date=date.today() + timedelta(days=30),
                )
                recert_count += 1

    logger.info(f"Created {recert_count} re-certification assignments")
    return {'recert_count': recert_count}


@shared_task
def cleanup_abandoned_attempts():
    """Weekly: Mark stale in-progress attempts as abandoned (>30 days inactive)."""
    from .models import TrainingAttempt

    threshold = timezone.now() - timedelta(days=30)
    updated = TrainingAttempt.objects.filter(
        status='in_progress',
        started_at__lt=threshold,
    ).update(status='abandoned')

    logger.info(f"Marked {updated} training attempts as abandoned")
    return {'abandoned_count': updated}
