# Generated by Django 5.2.8 on 2025-11-19 03:56

import apps.organizations.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(help_text="Organization/company name", max_length=200)),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Email domain (e.g., cccplc.net)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly organization identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("free", "Free Trial"),
                            ("starter", "Starter"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        help_text="Current subscription plan",
                        max_length=50,
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        default="trial",
                        help_text="Current subscription status",
                        max_length=20,
                    ),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of users allowed",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_storage_gb",
                    models.IntegerField(
                        default=10,
                        help_text="Maximum storage in GB",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "max_documents",
                    models.IntegerField(
                        default=1000,
                        help_text="Maximum number of documents allowed",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "trial_ends_at",
                    models.DateTimeField(
                        blank=True, help_text="When the trial period ends", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether organization is active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["domain"], name="org_domain_idx"),
                    models.Index(fields=["slug"], name="org_slug_idx"),
                    models.Index(fields=["subscription_status"], name="org_sub_status_idx"),
                    models.Index(fields=["created_at"], name="org_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address to invite (must match organization domain)",
                        max_length=254,
                        validators=[apps.organizations.validators.validate_business_email],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        help_text="Role to assign when invitation is accepted",
                        max_length=50,
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        help_text="Secure invitation token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the invitation expires (default: 7 days)"),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_invitations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["organization", "email"], name="invite_org_email_idx"),
                    models.Index(fields=["token"], name="invite_token_idx"),
                    models.Index(fields=["status"], name="invite_status_idx"),
                    models.Index(fields=["expires_at"], name="invite_expires_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                            ("member", "Member"),
                            ("viewer", "Viewer"),
                        ],
                        default="member",
                        help_text="User's role within the organization",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Whether membership is active"),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "organization_members",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(fields=["organization", "user"], name="org_member_idx"),
                    models.Index(fields=["role"], name="member_role_idx"),
                    models.Index(fields=["is_active"], name="member_active_idx"),
                ],
                "unique_together": {("organization", "user")},
            },
        ),
    ]
