# Generated by Django 5.2.8 on 2025-11-19 03:58

from django.db import migrations
from django.utils import timezone
from datetime import timedelta


def create_default_organization(apps, schema_editor):
    """
    Create default CCC PLC organization for existing data.

    This migration creates the default organization that will be used
    for all existing users in the system. New organizations will be
    created when users from different email domains register.
    """
    Organization = apps.get_model('organizations', 'Organization')

    # Create default CCC PLC organization
    default_org, created = Organization.objects.get_or_create(
        domain='cccplc.net',
        defaults={
            'name': 'CCC PLC',
            'slug': 'ccc-plc',
            'subscription_plan': 'enterprise',  # Default to enterprise for existing org
            'subscription_status': 'active',    # Active (not trial) for existing org
            'max_users': 500,                   # Higher limits for existing org
            'max_storage_gb': 1000,
            'max_documents': 50000,
            'is_active': True,
            'trial_ends_at': None,  # No trial for default org
        }
    )

    if created:
        print(f"✓ Created default organization: {default_org.name} ({default_org.domain})")
    else:
        print(f"✓ Default organization already exists: {default_org.name}")


def assign_users_to_default_organization(apps, schema_editor):
    """
    Assign all existing users to the default CCC PLC organization.
    Also create OrganizationMember records for proper role tracking.
    """
    Organization = apps.get_model('organizations', 'Organization')
    CustomUser = apps.get_model('users', 'CustomUser')
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')

    try:
        default_org = Organization.objects.get(domain='cccplc.net')
    except Organization.DoesNotExist:
        print("⚠ Default organization not found. Skipping user assignment.")
        return

    # Get all users without an organization
    users_without_org = CustomUser.objects.filter(organization__isnull=True)
    count = users_without_org.count()

    if count == 0:
        print("✓ No users need organization assignment")
        return

    # Assign all users to default organization
    users_without_org.update(organization=default_org)
    print(f"✓ Assigned {count} existing user(s) to {default_org.name}")

    # Create OrganizationMember records for all users
    # First user with is_staff=True becomes owner, rest become members
    members_created = 0
    owner_assigned = False

    for user in CustomUser.objects.filter(organization=default_org):
        # Determine role
        if not owner_assigned and user.is_staff:
            role = 'owner'
            owner_assigned = True
        elif user.is_staff or user.is_superuser:
            role = 'admin'
        else:
            role = 'member'

        # Create membership record
        OrganizationMember.objects.get_or_create(
            organization=default_org,
            user=user,
            defaults={
                'role': role,
                'is_active': user.is_active
            }
        )
        members_created += 1

    print(f"✓ Created {members_created} organization membership record(s)")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Remove organization assignments and delete default organization.
    """
    Organization = apps.get_model('organizations', 'Organization')
    CustomUser = apps.get_model('users', 'CustomUser')
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')

    # Remove all organization assignments from users
    CustomUser.objects.all().update(organization=None)
    print("✓ Removed organization assignments from all users")

    # Delete all organization members
    OrganizationMember.objects.all().delete()
    print("✓ Deleted all organization membership records")

    # Delete default organization
    Organization.objects.filter(domain='cccplc.net').delete()
    print("✓ Deleted default organization")


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("users", "0004_add_organization_fk"),  # Must run after organization FK is added
    ]

    operations = [
        migrations.RunPython(
            create_default_organization,
            reverse_code=reverse_migration
        ),
        migrations.RunPython(
            assign_users_to_default_organization,
            reverse_code=migrations.RunPython.noop
        ),
    ]
