# Generated by Django 5.2.8 on 2025-11-19 04:06

from django.db import migrations


def assign_departments_to_default_org(apps, schema_editor):
    """Assign all existing departments to default organization."""
    Organization = apps.get_model('organizations', 'Organization')
    Department = apps.get_model('users', 'Department')

    try:
        default_org = Organization.objects.get(domain='cccplc.net')
    except Organization.DoesNotExist:
        print("⚠ Default organization not found. Skipping department assignment.")
        return

    departments_without_org = Department.objects.filter(organization__isnull=True)
    count = departments_without_org.count()

    if count == 0:
        print("✓ No departments need organization assignment")
        return

    departments_without_org.update(organization=default_org)
    print(f"✓ Assigned {count} department(s) to {default_org.name}")


def assign_folders_to_default_org(apps, schema_editor):
    """Assign all existing folders to default organization."""
    Organization = apps.get_model('organizations', 'Organization')
    Folder = apps.get_model('folders', 'Folder')

    try:
        default_org = Organization.objects.get(domain='cccplc.net')
    except Organization.DoesNotExist:
        print("⚠ Default organization not found. Skipping folder assignment.")
        return

    folders_without_org = Folder.objects.filter(organization__isnull=True)
    count = folders_without_org.count()

    if count == 0:
        print("✓ No folders need organization assignment")
        return

    folders_without_org.update(organization=default_org)
    print(f"✓ Assigned {count} folder(s) to {default_org.name}")


def assign_documents_to_default_org(apps, schema_editor):
    """Assign all existing documents to default organization."""
    Organization = apps.get_model('organizations', 'Organization')
    Document = apps.get_model('documents', 'Document')

    try:
        default_org = Organization.objects.get(domain='cccplc.net')
    except Organization.DoesNotExist:
        print("⚠ Default organization not found. Skipping document assignment.")
        return

    documents_without_org = Document.objects.filter(organization__isnull=True)
    count = documents_without_org.count()

    if count == 0:
        print("✓ No documents need organization assignment")
        return

    documents_without_org.update(organization=default_org)
    print(f"✓ Assigned {count} document(s) to {default_org.name}")


def reverse_assignment(apps, schema_editor):
    """Reverse: Remove organization assignments from all data."""
    Department = apps.get_model('users', 'Department')
    Folder = apps.get_model('folders', 'Folder')
    Document = apps.get_model('documents', 'Document')

    Department.objects.all().update(organization=None)
    Folder.objects.all().update(organization=None)
    Document.objects.all().update(organization=None)
    print("✓ Removed organization assignments from all departments, folders, and documents")


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_create_default_organization"),
        ("users", "0005_add_organization_to_department"),
        ("folders", "0004_add_organization_to_folder"),
        ("documents", "0007_add_organization_to_document"),
    ]

    operations = [
        migrations.RunPython(
            assign_departments_to_default_org,
            reverse_code=reverse_assignment
        ),
        migrations.RunPython(
            assign_folders_to_default_org,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            assign_documents_to_default_org,
            reverse_code=migrations.RunPython.noop
        ),
    ]
