# Generated by Django 5.2.8 on 2025-11-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_assign_data_to_default_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country where organization is located", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="industry",
            field=models.CharField(
                blank=True, help_text="Industry/business sector", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="registration_number",
            field=models.CharField(
                blank=True, help_text="Company registration number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="tax_id",
            field=models.CharField(
                blank=True, help_text="Tax identification number", max_length=100
            ),
        ),
    ]
