# Generated by Django 5.2.8 on 2025-11-29 11:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_add_company_registration_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationFeatureFlags",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "advanced_search",
                    models.BooleanField(default=True, help_text="Full-text search with filters"),
                ),
                (
                    "ocr_processing",
                    models.BooleanField(default=True, help_text="OCR for scanned documents"),
                ),
                (
                    "version_control",
                    models.BooleanField(default=True, help_text="Document version history"),
                ),
                (
                    "folder_templates",
                    models.BooleanField(default=True, help_text="Pre-defined folder templates"),
                ),
                (
                    "external_sharing",
                    models.BooleanField(default=False, help_text="Share with external users"),
                ),
                (
                    "real_time_collaboration",
                    models.BooleanField(default=False, help_text="Real-time document editing"),
                ),
                (
                    "comments_annotations",
                    models.BooleanField(
                        default=True, help_text="Document comments and annotations"
                    ),
                ),
                (
                    "advanced_audit",
                    models.BooleanField(
                        default=False, help_text="Advanced audit logging and reports"
                    ),
                ),
                (
                    "retention_policies",
                    models.BooleanField(default=True, help_text="Document retention policies"),
                ),
                (
                    "legal_hold",
                    models.BooleanField(default=False, help_text="Legal hold capability"),
                ),
                (
                    "compliance_reports",
                    models.BooleanField(default=False, help_text="Compliance reporting features"),
                ),
                (
                    "data_classification",
                    models.BooleanField(default=True, help_text="Automatic data classification"),
                ),
                (
                    "basic_workflows",
                    models.BooleanField(default=True, help_text="Basic approval workflows"),
                ),
                (
                    "advanced_workflows",
                    models.BooleanField(default=False, help_text="Complex workflow designer"),
                ),
                (
                    "scheduled_tasks",
                    models.BooleanField(default=False, help_text="Scheduled automation tasks"),
                ),
                ("api_access", models.BooleanField(default=False, help_text="REST API access")),
                ("webhooks", models.BooleanField(default=False, help_text="Webhook integrations")),
                (
                    "basic_analytics",
                    models.BooleanField(default=True, help_text="Basic usage analytics"),
                ),
                (
                    "advanced_analytics",
                    models.BooleanField(default=False, help_text="Advanced analytics and insights"),
                ),
                (
                    "custom_reports",
                    models.BooleanField(default=False, help_text="Custom report builder"),
                ),
                (
                    "export_reports",
                    models.BooleanField(default=True, help_text="Export reports to PDF/Excel"),
                ),
                (
                    "custom_roles",
                    models.BooleanField(default=True, help_text="Create custom roles"),
                ),
                (
                    "sso_integration",
                    models.BooleanField(default=False, help_text="SSO/SAML integration"),
                ),
                (
                    "custom_branding",
                    models.BooleanField(
                        default=False, help_text="Custom branding and white-labeling"
                    ),
                ),
                (
                    "priority_support",
                    models.BooleanField(default=False, help_text="Priority customer support"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_flags",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Feature Flags",
                "verbose_name_plural": "Organization Feature Flags",
                "db_table": "organization_feature_flags",
            },
        ),
        migrations.CreateModel(
            name="OrganizationSecurityPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "password_min_length",
                    models.PositiveIntegerField(
                        default=8,
                        help_text="Minimum password length",
                        validators=[
                            django.core.validators.MinValueValidator(6),
                            django.core.validators.MaxValueValidator(32),
                        ],
                    ),
                ),
                (
                    "password_require_uppercase",
                    models.BooleanField(
                        default=True, help_text="Require at least one uppercase letter"
                    ),
                ),
                (
                    "password_require_lowercase",
                    models.BooleanField(
                        default=True, help_text="Require at least one lowercase letter"
                    ),
                ),
                (
                    "password_require_numbers",
                    models.BooleanField(default=True, help_text="Require at least one number"),
                ),
                (
                    "password_require_special",
                    models.BooleanField(
                        default=False, help_text="Require at least one special character"
                    ),
                ),
                (
                    "password_expiry_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Password expiry in days (0 = never expires)",
                        validators=[django.core.validators.MaxValueValidator(365)],
                    ),
                ),
                (
                    "password_history_count",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Number of previous passwords to prevent reuse",
                        validators=[django.core.validators.MaxValueValidator(24)],
                    ),
                ),
                (
                    "mfa_required",
                    models.BooleanField(default=False, help_text="Require MFA for all users"),
                ),
                (
                    "mfa_required_for_admins",
                    models.BooleanField(default=True, help_text="Require MFA for admin users"),
                ),
                (
                    "mfa_grace_period_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Days to enable MFA after account creation",
                        validators=[django.core.validators.MaxValueValidator(30)],
                    ),
                ),
                (
                    "allowed_mfa_methods",
                    models.JSONField(
                        default=list, help_text="Allowed MFA methods: ['totp', 'sms', 'email']"
                    ),
                ),
                (
                    "session_timeout_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Session timeout in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "max_concurrent_sessions",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum concurrent sessions per user",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "require_reauthentication",
                    models.BooleanField(
                        default=True, help_text="Require re-authentication for sensitive operations"
                    ),
                ),
                (
                    "max_login_attempts",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Failed attempts before account lockout",
                        validators=[
                            django.core.validators.MinValueValidator(3),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "lockout_duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Account lockout duration in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "login_notification_enabled",
                    models.BooleanField(default=True, help_text="Notify users on new login"),
                ),
                (
                    "suspicious_activity_alerts",
                    models.BooleanField(
                        default=True, help_text="Alert admins on suspicious login activity"
                    ),
                ),
                (
                    "ip_whitelist_enabled",
                    models.BooleanField(default=False, help_text="Enable IP whitelisting"),
                ),
                (
                    "ip_whitelist",
                    models.JSONField(default=list, help_text="List of allowed IP addresses/ranges"),
                ),
                (
                    "data_export_restricted",
                    models.BooleanField(default=False, help_text="Restrict bulk data exports"),
                ),
                (
                    "require_encryption",
                    models.BooleanField(
                        default=True, help_text="Require encryption for all documents"
                    ),
                ),
                (
                    "audit_log_retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="Audit log retention period in days",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(2555),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_policy",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Security Policy",
                "verbose_name_plural": "Organization Security Policies",
                "db_table": "organization_security_policies",
            },
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Organization logo (recommended: 200x200px)",
                        null=True,
                        upload_to="organization_logos/",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Primary brand color in hex format",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#1E40AF",
                        help_text="Secondary brand color in hex format",
                        max_length=7,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email for the organization",
                        max_length=254,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Primary contact phone number", max_length=50
                    ),
                ),
                ("website", models.URLField(blank=True, help_text="Organization website URL")),
                ("address_line1", models.CharField(blank=True, max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", help_text="Organization default timezone", max_length=50
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="YYYY-MM-DD", help_text="Default date format", max_length=20
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="Default language code", max_length=10
                    ),
                ),
                (
                    "default_confidentiality",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("internal", "Internal"),
                            ("confidential", "Confidential"),
                            ("highly_confidential", "Highly Confidential"),
                        ],
                        default="internal",
                        help_text="Default confidentiality level for new documents",
                        max_length=50,
                    ),
                ),
                (
                    "require_classification",
                    models.BooleanField(
                        default=True, help_text="Require documents to be classified on upload"
                    ),
                ),
                (
                    "allow_external_sharing",
                    models.BooleanField(
                        default=False, help_text="Allow sharing documents with external users"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Settings",
                "verbose_name_plural": "Organization Settings",
                "db_table": "organization_settings",
            },
        ),
    ]
