# Generated by Django 5.2.8 on 2025-11-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="compliancealert",
            new_name="compliance__target__cba9ee_idx",
            old_name="compliance__target__a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancealert",
            new_name="compliance__alert_t_ac8fc2_idx",
            old_name="compliance__alert_t_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancescore",
            new_name="compliance__scope_9d0de9_idx",
            old_name="compliance__scope_c4c0c9_idx",
        ),
        migrations.RenameIndex(
            model_name="compliancescore",
            new_name="compliance__scope_i_b57610_idx",
            old_name="compliance__scope_i_f4b0c8_idx",
        ),
        migrations.RenameIndex(
            model_name="documentcompliancecheck",
            new_name="compliance__documen_d97845_idx",
            old_name="compliance__documen_e4c0c9_idx",
        ),
        migrations.RenameIndex(
            model_name="documentcompliancecheck",
            new_name="compliance__check_t_3d0019_idx",
            old_name="compliance__check_t_f4b0c8_idx",
        ),
    ]
